"""EEP profile fragment: A5 HVAC + gateway control (A5-20 / A5-38 / A5-3F).

Merged into the full PROFILES by the package __init__. Built with the _build helpers;
checked by tests/protocol/test_profiles.py.
"""

# ruff: noqa
from enocean2mqtt.protocol.profiles._build import LRNB_4BS, case, cond, enum, field, profile

PROFILES = {
    (0xa5, 0x20, 0x01): profile(0xa5, 0x20, 0x01, 'Battery Powered Actuator',
        case((
            LRNB_4BS,
            field('CV', 'Current Value', 0, 8, 'value', unit='%', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('SO', 'Service On', 8, 1, 'enum', items=(enum('on', 1),)),
            field('ENIE', 'Energy input enabled', 9, 1, 'enum', items=(enum('true', 1),)),
            field('ES', 'Energy Storage', 10, 1, 'enum', items=(enum('true', 1),)),
            field('BCAP', 'Battery capacity', 11, 1, 'enum', items=(enum('true', 0),)),
            field('CCO', 'Contact, cover open', 12, 1, 'enum', items=(enum('true', 1),)),
            field('FTS', 'Failure temperature sensor, out off range', 13, 1, 'enum', items=(enum('true', 1),)),
            field('DWO', 'Detection, window open', 14, 1, 'enum', items=(enum('true', 1),)),
            field('ACO', 'Actuator obstructed', 15, 1, 'enum', items=(enum('true', 1),)),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=40.0),
        ), direction=1),
        case((
            LRNB_4BS,
            field('SP', 'Valve position or Temperature Setpoint', 0, 8, 'value', unit='% or °C', range_min=0.0, scale_min=0.0),
            field('TMP', 'Temperature  from RCU', 8, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('RIN', 'Run init sequence', 16, 1, 'enum', items=(enum('true', 1),)),
            field('LFS', 'Lift set', 17, 1, 'enum', items=(enum('true', 1),)),
            field('VO', 'Valve open / maintenance', 18, 1, 'enum', items=(enum('true', 1),)),
            field('VC', 'Valve closed', 19, 1, 'enum', items=(enum('true', 1),)),
            field('SB', 'Summer bit, Reduction of energy consumption', 20, 1, 'enum', items=(enum('true', 1),)),
            field('SPS', 'Set Point Selection', 21, 1, 'enum', items=(enum('Valve position (0-100%). Unit respond to controller.', 0), enum('Temperature set point 0...40°C. Unit respond to room sensor and use internal PI loop.', 1))),
            field('SPN', 'Set point inverse', 22, 1, 'enum', items=(enum('true', 1),)),
            field('RCU', 'Select function', 23, 1, 'enum', items=(enum('RCU', 0), enum('service on', 1))),
        ), direction=2),
    ),
    (0xa5, 0x20, 0x02): profile(0xa5, 0x20, 0x02, 'Basic Actuator',
        case((
            LRNB_4BS,
            field('AV', 'Actual Value', 0, 8, 'value', unit='%', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('SPI', 'Set point inverse', 22, 1, 'enum', items=(enum('true', 1),)),
        ), direction=1),
        case((
            LRNB_4BS,
            field('VSP', 'Valve Set point', 0, 8, 'value', unit='%', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('VSP', 'Set point inverse', 22, 1, 'enum', items=(enum('true', 1),)),
        ), direction=2),
    ),
    (0xa5, 0x20, 0x03): profile(0xa5, 0x20, 0x03, 'Line powered Actuator',
        case((
            LRNB_4BS,
            field('AV', 'Actual valve', 0, 8, 'value', unit='%', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=40.0),
        ), direction=1),
        case((
            field('', 'Set Point Inverse', 22, 1, 'enum', items=(enum('true', 1),)),
            field('SPS', 'Set Point Selection', 21, 1, 'enum', items=(enum('Actuator Setpoint (0-100%); Unit respond to controller.', 0), enum('Temperature Setpoint 0...+40°C; Unit respond to room sensor and use internal PI loop.', 1))),
            LRNB_4BS,
            field('ATS', 'Actuator or Temperature Setpoint', 0, 8, 'value', unit='% or °C', range_min=0.0, scale_min=0.0),
            field('TMPRC', 'Temperature  from RCU', 8, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
        ), direction=2),
    ),
    (0xa5, 0x20, 0x04): profile(0xa5, 0x20, 0x04, 'Heating Radiator Valve Actuating Drive with Feed and Room Temperature Measurement, Local Set Point Control and Display',
        case((
            LRNB_4BS,
            field('CP', 'Current Position', 0, 8, 'value', unit='%', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('FTS', 'Feed Temperature OR Temperature Set Point', 8, 8, 'value', unit='°C', range_min=0.0, range_max=255.0),
            field('TMPFC', 'Room Temperature OR Failure Code', 16, 8, 'enum', items=(enum('', minimum=0, maximum=255, scale_min=10.0, scale_max=30.0, unit='°C'), enum('Reserved'), enum('Measurement error', 17), enum('Battery empty', 18), enum('Reserved', 19), enum('Frost protection', 20), enum('Reserved'), enum('Blocked valve', 33), enum('Reserved'), enum('End point detection error', 36), enum('Reserved'), enum('No valve', 40), enum('Reserved'), enum('Not taught in', 49), enum('Reserved'), enum('No response from controller', 53), enum('Teach-in error', 54), enum('Reserved'))),
            field('MST', 'Measurement Status', 24, 1, 'enum', items=(enum('Active', 0), enum('Inactive', 1))),
            field('STR', 'Status Request', 25, 1, 'enum', items=(enum('No change', 0), enum('Status requested', 1))),
            field('BLS', 'Button Lock Status', 29, 1, 'enum', items=(enum('Unlocked', 0), enum('Locked', 1))),
            field('TS', 'Temperature Selection', 30, 1, 'enum', items=(enum('Feed temperature', 0), enum('Temperature set point', 1))),
            field('FL', 'Failure', 31, 1, 'enum', items=(enum('No failure (TMP is transmitted)', 0), enum('failure (FC is transmitted)', 1))),
        ), direction=1),
        case((
            field('POS', 'Valve Position', 0, 8, 'value', unit='%', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('TSP', 'Temperature Set Point', 8, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=10.0, scale_max=30.0),
            LRNB_4BS,
            field('MC', 'Measurement Control', 17, 1, 'enum', items=(enum('Enable', 0), enum('Disable', 1))),
            field('WUC', 'Wake-up Cycle', 18, 6, 'enum', items=(enum('10 sec', 0), enum('60 sec', 1), enum('90 sec', 2), enum('120 sec', 3), enum('150 sec', 4), enum('180 sec', 5), enum('210 sec', 6), enum('240 sec', 7), enum('270 sec', 8), enum('300 sec (5 min)', 9), enum('330 sec', 10), enum('360 sec', 11), enum('390 sec', 12), enum('420 sec', 13), enum('450 sec', 14), enum('480 sec', 15), enum('510 sec', 16), enum('540 sec', 17), enum('570 sec', 18), enum('600 sec (10 min)', 19), enum('630 sec', 20), enum('660 sec', 21), enum('690 sec', 22), enum('720 sec', 23), enum('750 sec', 24), enum('780 sec', 25), enum('810 sec', 26), enum('840 sec', 27), enum('870 sec', 28), enum('900 sec (15 min)', 29), enum('930 sec', 30), enum('960 sec', 31), enum('990 sec', 32), enum('1020 sec', 33), enum('1050 sec', 34), enum('1080 sec', 35), enum('1110 sec', 36), enum('1140 sec', 37), enum('1170 sec', 38), enum('1200 sec (20 min)', 39), enum('1230 sec', 40), enum('1260 sec', 41), enum('1290 sec', 42), enum('1320 sec', 43), enum('1350 sec', 44), enum('1380 sec', 45), enum('1410 sec', 46), enum('1440 sec', 47), enum('1470 sec', 48), enum('1500 sec (25 min)', 49), enum('3 hrs', 50), enum('6 hrs', 51), enum('9 hrs', 52), enum('12 hrs', 53), enum('15 hrs', 54), enum('18 hrs', 55), enum('21 hrs', 56), enum('24 hrs', 57), enum('27 hrs', 58), enum('30 hrs', 59), enum('33 hrs', 60), enum('36 hrs', 61), enum('39 hrs', 62), enum('42 hrs (max)', 63))),
            field('DSO', 'Display Orientation', 26, 2, 'enum', items=(enum('0°', 0), enum('90°', 1), enum('180°', 2), enum('270°', 3))),
            field('BLC', 'Button Lock Control', 29, 1, 'enum', items=(enum('Unlocked', 0), enum('Locked', 1))),
            field('SER', 'Service Command', 30, 2, 'enum', items=(enum('No change', 0), enum('Open valve', 1), enum('Run initialisation', 2), enum('Close valve', 3))),
        ), direction=2),
    ),
    (0xa5, 0x20, 0x05): profile(0xa5, 0x20, 0x05, 'Ventilation Unit',
        case((
            LRNB_4BS,
            field('ASP', 'Actual speed setting', 0, 3, 'enum', items=(enum('Minimum speed / away', 0), enum('Speed 1 / low', 1), enum('Speed 2 / mid', 2), enum('Speed 3 / high', 3), enum('Max speed', 4), enum('Auto', 5), enum('Not used', 6), enum('Not used', 7))),
            field('ASPT', 'Actual speed timer setting', 3, 3, 'enum', items=(enum('No timer set or expired', 0), enum('1..10 min left', 1), enum('11..20 min left', 2), enum('21..30 min left', 3), enum('31..40 min left', 4), enum('41..50 min left', 5), enum('51..60 min left', 6), enum('> 60 min left', 7))),
            field('E-NBAT', 'Node low battery', 11, 1, 'enum', items=(enum('No error', 0), enum('Error', 1))),
            field('E-NCOM', 'Node comm. error', 12, 1, 'enum', items=(enum('No error', 0), enum('Error', 1))),
            field('E-SENS', 'Sensor error', 13, 1, 'enum', items=(enum('No error', 0), enum('Error', 1))),
            field('E-FSPD', 'Fan speed error', 14, 1, 'enum', items=(enum('No error', 0), enum('Error', 1))),
            field('ERR', 'Error', 15, 1, 'enum', items=(enum('No error', 0), enum('Error', 1))),
            field('FLTR', 'Filter condition', 16, 8, 'enum', items=(enum('Filter needs replacement', 0), enum('% dirty..clean filter', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=254), enum('No filter present', 255))),
            field('AUTO', 'Auto speed supported', 24, 1, 'enum', items=(enum('Auto speed not supported', 0), enum('Auto speed supported', 1))),
            field('BPASS', 'By-pass active', 25, 1, 'enum', items=(enum('Summer bypass not active', 0), enum('Summer bypass active', 1))),
            field('FROST', 'Frost protection', 26, 1, 'enum', items=(enum('Frost protection not active', 0), enum('Frost protection active', 1))),
        ), direction=1),
        case((
            LRNB_4BS,
            field('NSP', 'New speed setting', 0, 3, 'enum', items=(enum('Minimum speed / away', 0), enum('Speed 1 / low', 1), enum('Speed 2 / mid', 2), enum('Speed 3 / high', 3), enum('Max speed', 4), enum('Auto', 5), enum('Not used', 6), enum('No change', 7))),
            field('NSPT', 'New speed timer setting', 3, 5, 'enum', items=(enum('No timer / no change', 0), enum('10..60 min', minimum=1, maximum=6), enum('2..24 hrs', minimum=7, maximum=29), enum('Not used', minimum=30, maximum=31))),
            field('RSTE', 'Reset error', 24, 1, 'enum', items=(enum('Don’t reset error', 0), enum('Reset error', 1))),
            field('RSTF', 'Reset filter timer', 25, 1, 'enum', items=(enum('Don’t reset filter timer', 0), enum('Reset filter timer', 1))),
        ), direction=2),
    ),
    (0xa5, 0x20, 0x06): profile(0xa5, 0x20, 0x06, 'Harvesting-powered actuator with local temperature offset control (BI-DIR)',
        case((
            field('CV', 'Current Value', 0, 8, 'value', unit='%', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('LOM', 'Local Offset Mode', 8, 1, 'enum', items=(enum('LO is relative - Offsettemperature', 0), enum('LO is absolute - Absoluttemperature', 1))),
            field('LO', 'Local Offset', 9, 7, 'enum', items=(enum('Temperature setpoint °C +/- local offset °C', minimum=0, maximum=80, scale_min=0.0, scale_max=40.0, unit='°C'), enum('Local Offset 0C', 0), enum('Local Offset 1C', 1), enum('Local Offset 2C', 2), enum('Local Offset 3C', 3), enum('Local Offset 4C', 4), enum('Local Offset 5C', 5), enum('Local Offset -5C', 123), enum('Local Offset -4C', 124), enum('Local Offset -3C', 125), enum('Local Offset -2CC', 126), enum('Local Offset -1C', 127))),
            field('TMP', 'Temperature', 16, 8, 'enum', items=(enum('Local ambient temperature', minimum=0, maximum=80, scale_min=0.0, scale_max=40.0, unit='°C'), enum('Feed temperature', minimum=0, maximum=160, scale_min=0.0, scale_max=80.0, unit='°C'))),
            field('TSL', 'Tempertature Selection', 24, 1, 'enum', items=(enum('Ambient Sensor Temperature', 0), enum('Feed Sensor Temperature', 1))),
            field('ENIE', 'Energy Input Enabled', 25, 1, 'enum', items=(enum('Not Harvesting', 0), enum('Harvesting active', 1))),
            field('ES', 'Energy Storage', 26, 1, 'enum', items=(enum('Low - almost discharged', 0), enum('Sufficently charged', 1))),
            field('DWO', 'Window open detection', 27, 1, 'enum', items=(enum('NO window open detected', 0), enum('Window open detected', 1))),
            LRNB_4BS,
            field('RCE', 'Radio Com Error', 29, 1, 'enum', items=(enum('Radio communication is stable', 0), enum('6 or more consecutive communication erros have occured', 1))),
            field('RSS', 'Radio Signal strength', 30, 1, 'enum', items=(enum('Radio signal is strong', 0), enum('Radio signal is weak under -77dBm', 1))),
            field('ACO', 'Actuator obstructed', 31, 1, 'enum', items=(enum('Actuator working correctly', 0), enum('Actuator blocked', 1))),
        ), direction=1),
        case((
            field('SP', 'Setpoint', 0, 8, 'enum', items=(enum('Valve position', minimum=0, maximum=100, scale_min=0.0, scale_max=100.0, unit='%'), enum('Temperature setpoinz', minimum=0, maximum=80, scale_min=0.0, scale_max=40.0, unit='°C'))),
            field('TMP', 'Room temperature from contrul unit', 8, 8, 'value', unit='%', range_min=0.0, range_max=160.0, scale_min=0.0, scale_max=40.0),
            field('REF', 'Reference run', 16, 1, 'enum', items=(enum('Normal operation', 0), enum('Reference run', 1))),
            field('RFC', 'RF Communication intervall', 17, 4, 'enum', items=(enum('Auto', 0), enum('2 minutes', 1), enum('5 minutes', 2), enum('10 minutes', 3), enum('20 minutes', 4), enum('30 minutes', 5), enum('60 minutes', 6), enum('120 minutes', 7))),
            field('SB', 'Initiate summer mode Bit', 20, 1, 'enum', items=(enum('Normal operation', 0), enum('Summer mode with 8hours radio duty cycle', 1))),
            field('SPS', 'Set point selection', 21, 1, 'enum', items=(enum('Valve position mode', 0), enum('Temperature setpoint', 1))),
            field('TSL', 'Temperature Selection', 22, 1, 'enum', items=(enum('Request ambient temperature', 0), enum('Request feedtemperature', 1))),
            field('SBY', 'Standbye', 23, 1, 'enum', items=(enum('Normal operation', 0), enum('Enter standbye', 1))),
            LRNB_4BS,
        ), direction=2),
    ),
    (0xa5, 0x20, 0x10): profile(0xa5, 0x20, 0x10, 'Generic HVAC Interface',
        case((
            LRNB_4BS,
            field('MD', 'Mode', 0, 8, 'enum', items=(enum('Auto', 0), enum('Heat', 1), enum('Morning Warmup', 2), enum('Cool', 3), enum('Night Purge', 4), enum('Precool', 5), enum('Off', 6), enum('Test', 7), enum('Emergency Heat', 8), enum('Fan only', 9), enum('Free cool', 10), enum('Ice', 11), enum('Max heat', 12), enum('Economic heat/cool', 13), enum('Dehumidification (dry)', 14), enum('Calibration', 15), enum('Emergency cool', 16), enum('Emergency steam', 17), enum('max cool', 18), enum('Hvc load', 19), enum('no load', 20), enum('reserved', minimum=21, maximum=30), enum('Auto Heat', 31), enum('Auto Cool', 32), enum('reserved', minimum=33, maximum=254), enum('N/A', 255))),
            field('VPS', 'Vane position', 8, 4, 'enum', items=(enum('Auto', 0), enum('Horizontal', 1), enum('Pos2', 2), enum('Pos3', 3), enum('Pos4', 4), enum('Vertical', 5), enum('Swing', 6), enum('Reserved', minimum=7, maximum=10), enum('Vertical swing', 11), enum('Horizontal swing', 12), enum('Horizontal and vertical swing', 13), enum('Stop swing', 14), enum('N/A', 15))),
            field('FANSP', 'Fan Speed', 12, 4, 'enum', items=(enum('Auto', 0), enum('Up to 14 fan speeds being 1 the lowest', minimum=1, maximum=14), enum('N/A', 15))),
            field('CVAR', 'Control variable', 16, 8, 'value', unit='%', range_min=0.0, scale_min=0.0, scale_max=100.0),
            field('RO', 'Room occupancy', 29, 2, 'enum', items=(enum('Occupied', 0), enum('StandBy (waiting to perform action)', 1), enum('Unoccupied (action performed)', 2), enum('Off (no occupancy and no action)', 3))),
            field('O/I', 'On/Off', 31, 1, 'enum', items=(enum('off (the unit is not running)', 0), enum('on', 1))),
        ), direction=1),
        case((
            LRNB_4BS,
            field('MD', 'Mode', 0, 8, 'enum', items=(enum('Auto', 0), enum('Heat', 1), enum('Morning Warmup', 2), enum('Cool', 3), enum('Night Purge', 4), enum('Precool', 5), enum('Off', 6), enum('Test', 7), enum('Emergency Heat', 8), enum('Fan only', 9), enum('Free cool', 10), enum('Ice', 11), enum('Max heat', 12), enum('Economic heat/cool', 13), enum('Dehumidification (dry)', 14), enum('Calibration', 15), enum('Emergency cool', 16), enum('Emergency steam', 17), enum('max cool', 18), enum('Hvc load', 19), enum('no load', 20), enum('reserved', minimum=21, maximum=30), enum('Auto Heat', 31), enum('Auto Cool', 32), enum('reserved', minimum=33, maximum=254), enum('N/A', 255))),
            field('VPS', 'Vane position', 8, 4, 'enum', items=(enum('Auto', 0), enum('Horizontal', 1), enum('Pos2', 2), enum('Pos3', 3), enum('Pos4', 4), enum('Vertical', 5), enum('Swing', 6), enum('Reserved', minimum=7, maximum=10), enum('Vertical swing', 11), enum('Horizontal swing', 12), enum('Horizontal and vertical swing', 13), enum('Stop swing', 14), enum('N/A', 15))),
            field('FANSP', 'Fan Speed', 12, 4, 'enum', items=(enum('Auto', 0), enum('Up to 14 fan speeds being 1 the lowest', minimum=1, maximum=14), enum('N/A', 15))),
            field('CVAR', 'Control variable', 16, 8, 'value', unit='%', range_min=0.0, scale_min=0.0, scale_max=100.0),
            field('RO', 'Room occupancy', 29, 2, 'enum', items=(enum('Occupied', 0), enum('StandBy (waiting to perform action)', 1), enum('Unoccupied (action performed)', 2), enum('Off (no occupancy and no action)', 3))),
            field('O/I', 'On/Off', 31, 1, 'enum', items=(enum('off', 0), enum('on', 1))),
        ), direction=2),
    ),
    (0xa5, 0x20, 0x11): profile(0xa5, 0x20, 0x11, 'Generic HVAC Interface – Error Control',
        case((
            field('DRC', 'Disable remote controller', 29, 1, 'enum', items=(enum('Enable Remote controller', 0), enum('Disable Remote controller', 1))),
            LRNB_4BS,
            field('EXDS', 'External disablement', 23, 1, 'enum', items=(enum('Not disabled', 0), enum('Disabled', 1))),
            field('WC', 'Window contact', 30, 1, 'enum', items=(enum('Windows opened', 0), enum('Windows closed', 1))),
        ), direction=1),
        case((
            field('RCD', 'Remote controller Disablement', 29, 1, 'enum', items=(enum('Remote controller enabled', 0), enum('Remote controller disabled', 1))),
            LRNB_4BS,
            field('ERR', 'Error Code', 0, 16, 'value', unit='N/A', range_min=0.0, range_max=65535.0, scale_min=0.0, scale_max=65535.0),
            field('RES', 'Reserved', 16, 4, 'enum', items=(enum('Reserved'),)),
            field('OD', 'Other disablement', 20, 1, 'enum', items=(enum('Not disabled', 0), enum('Disabled', 1))),
            field('WCD', 'Window contact disablement', 21, 1, 'enum', items=(enum('Not disabled', 0), enum('Disabled', 1))),
            field('KCD', 'Key card disablement', 22, 1, 'enum', items=(enum('Not disabled', 0), enum('Disabled', 1))),
            field('ED', 'External disablement', 23, 1, 'enum', items=(enum('Not disabled', 0), enum('Disabled', 1))),
            field('WC', 'Window contact', 30, 1, 'enum', items=(enum('Windows opened', 0), enum('Windows closed', 1))),
            field('AS', 'Alarm State', 31, 1, 'enum', items=(enum('Ok', 0), enum('Error', 1))),
        ), direction=2),
    ),
    (0xa5, 0x20, 0x12): profile(0xa5, 0x20, 0x12, 'Temperature Controller Input',
        case((
            LRNB_4BS,
            field('CV', 'Control Variable override', 0, 8, 'value', unit='%', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=100.0),
            field('FANOR', 'FanStage override', 8, 8, 'enum', items=(enum('Stage 0', 0), enum('Stage 1', 1), enum('Stage 2', 2), enum('Stage 3', 3), enum('auto', 31), enum('not available', 255))),
            field('SPS', 'Setpoint shift', 16, 8, 'value', unit='°K', range_min=0.0, range_max=255.0, scale_min=-10.0, scale_max=10.0),
            field('FANOR', 'Fan override', 24, 1, 'enum', items=(enum('Automatic', 0), enum('Override Fan DB2', 1))),
            field('CTM', 'Controller mode', 25, 2, 'enum', items=(enum('Auto mode', 0), enum('Heating', 1), enum('Cooling', 2), enum('Off', 3))),
            field('CST', 'Controller state', 27, 1, 'enum', items=(enum('Automatic', 0), enum('Override control variable DB3', 1))),
            field('ERH', 'Energy hold-off / Dew point', 29, 1, 'enum', items=(enum('Normal', 0), enum('Energy hold-off/ Dew point', 1))),
            field('RO', 'Room occupancy', 30, 2, 'enum', items=(enum('Occupied', 0), enum('Unoccupied', 1), enum('StandBy', 2), enum('Frost', 3))),
        )),
    ),
    (0xa5, 0x38, 0x08): profile(0xa5, 0x38, 0x08, 'Gateway',
        case((
            LRNB_4BS,
            field('COM', 'Command', 0, 8, 'enum', items=(enum('', 1),)),
            field('TIM', 'Time', 8, 16, 'value', unit='s', range_min=1.0, range_max=65535.0, scale_min=0.1, scale_max=6553.5),
            field('LCK', 'Lock/Unlock', 29, 1, 'enum', items=(enum('Unlock', 0), enum('Lock', 1))),
            field('DEL', 'Delay or duration', 30, 1, 'enum', items=(enum('Duration', 0), enum('Delay', 1))),
            field('SW', 'Switching Command', 31, 1, 'enum', items=(enum('Off', 0), enum('On', 1))),
        )),
        case((
            LRNB_4BS,
            field('COM', 'Command', 0, 8, 'enum', items=(enum('', 2),)),
            field('EDIM', 'Dimming value', 8, 8, 'value', unit='%', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=100.0),
            field('RMP', 'Ramping time', 16, 8, 'value', unit='s', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('EDIM R', 'Dimming Range', 29, 1, 'enum', items=(enum('Absolute value', 0), enum('Relative value', 1))),
            field('STR', 'Store final value', 30, 1, 'enum', items=(enum('No', 0), enum('Yes', 1))),
            field('SW', 'Switching Command', 31, 1, 'enum', items=(enum('Off', 0), enum('On', 1))),
        ), conditions=(cond('data', 0, 8, 2),)),
        case((
            LRNB_4BS,
            field('COM', 'Command', 0, 8, 'enum', items=(enum('', 3),)),
            field('SP', 'Setpoint', 16, 8, 'value', unit='K', range_min=0.0, range_max=255.0, scale_min=-12.7, scale_max=12.8),
        ), conditions=(cond('data', 0, 8, 3),)),
        case((
            LRNB_4BS,
            field('COM', 'Command', 0, 8, 'enum', items=(enum('', 4),)),
            field('BSP', 'Basic Setpoint', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=51.2),
        ), conditions=(cond('data', 0, 8, 4),)),
        case((
            LRNB_4BS,
            field('COM', 'Command', 0, 8, 'enum', items=(enum('', 5),)),
            field('CVOV', 'Control variable override', 16, 8, 'value', unit='%', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=100.0),
            field('CM', 'Controller mode', 25, 2, 'enum', items=(enum('Automatic mode selection', 0), enum('Heating', 1), enum('Cooling', 2), enum('Off', 3))),
            field('CS', 'Controller state', 27, 1, 'enum', items=(enum('Automatic', 0), enum('Override', 1))),
            field('ENHO', 'Energy hold off', 29, 1, 'enum', items=(enum('Normal', 0), enum('Energy holdoff/ Dew point', 1))),
            field('RMOCC', 'Room occupancy', 30, 2, 'enum', items=(enum('Occupied', 0), enum('Unoccupied', 1), enum('Standby', 2))),
        ), conditions=(cond('data', 0, 8, 5),)),
        case((
            LRNB_4BS,
            field('COM', 'Command', 0, 8, 'enum', items=(enum('', 6),)),
            field('FO', 'FanStage override', 16, 8, 'enum', items=(enum('Stage 0', 0), enum('Stage 1', 1), enum('Stage 2', 2), enum('Stage 3', 3), enum('Auto', 255))),
        ), conditions=(cond('data', 0, 8, 6),)),
        case((
            LRNB_4BS,
            field('COM', 'Command', 0, 8, 'enum', items=(enum('Shutters / Blinds', 7),)),
            field('P1', 'Parameter 1', 8, 8, 'enum', items=(enum('Func. 00: -- not used –-'),)),
            field('P2', 'Parameter 2', 16, 8, 'enum', items=(enum('Func. 00: -- not used –-'),)),
            field('FUNC', 'Function', 24, 4, 'enum', items=(enum('Do nothing, status request', 0), enum('Blind stops', 1), enum('Blind opens', 2), enum('Blind closes', 3), enum('Blind drives to position with angle value (see remark 2)', 4), enum('Blind opens for time (position value) and angle (angle value)', 5), enum('Blind closes for time (position value) and angle (angle value)', 6), enum('Set Runtime parameters (see remark 3)', 7), enum('Set angle configuration (see remark 3)', 8), enum('Set Min, Max values (see remark 4)', 9), enum('Set slat angle for SHUT and OPEN position (see remark 5)', 10), enum('Set position logic (see remark 6)', 11))),
            field('SSF', 'Send status flag', 29, 1, 'enum', items=(enum('Send new status of device', 0), enum('Send no status (e.g. Global central commands)', 1))),
            field('PAF', 'Pos. and Angle flag', 30, 1, 'enum', items=(enum('No Angle and position value available', 0), enum('Angle and position value available', 1))),
            field('SMF', 'Service Mode Flag', 31, 1, 'enum', items=(enum('Normal operation', 0), enum('Service mode: The module disables all\n                      senders, except this sender, which has set the service mode.\n                      (For example for maintenance)', 1))),
        ), conditions=(cond('data', 0, 8, 7),)),
    ),
    (0xa5, 0x38, 0x09): profile(0xa5, 0x38, 0x09, 'Extended Lighting-Control',
        case((
            LRNB_4BS,
            field('P1', 'Parameter 1', 0, 8, 'enum', items=(enum('Func. 00: -- not used –-'),)),
            field('P2', 'Parameter 2', 8, 8, 'enum', items=(enum('Func. 00: -- not used –-'),)),
            field('P3', 'Parameter 3', 16, 8, 'enum', items=(enum('Func. 00: -- not used –-'),)),
            field('FUNC', 'Function', 24, 4, 'enum', items=(enum('Do nothing, status request', 0), enum('Switched off', 1), enum('Switched on (Memory value)', 2), enum('Dimming up with ramping time', 3), enum('Dimming down with ramping time', 4), enum('Dimming stops', 5), enum('Set dimmer-value and ramping time', 6), enum('Set RGB values (see remark 1)', 7), enum('Scene function (see remark 2)', 8), enum('Set minimal and maximal dimmer-value (see remark 3)', 9), enum('Set the operating hours of the lamp (see remark 4)', 10), enum('Locking local operations (see remark 5)', 11), enum('Set a new value for the energy metering\n                    (overwrite the actual value with the selected unit)', 12))),
            field('SSF', 'Send status flag', 29, 1, 'enum', items=(enum('Send new status of device', 0), enum('Send no status (e.g. Global central commands)', 1))),
            field('SFV', 'Store final value', 30, 1, 'enum', items=(enum('No', 0), enum('Yes', 1))),
            field('SMF', 'Service Mode Flag', 31, 1, 'enum', items=(enum('Normal operation', 0), enum('Service mode: The module disables all\n                      senders, except this sender, which has set the service mode.\n                      (For example for maintenance)', 1))),
        )),
    ),
    (0xa5, 0x3f, 0x00): profile(0xa5, 0x3f, 0x00, 'Radio Link Test',
        case((
            LRNB_4BS,
            field('MSGID', 'MSG_ID', 29, 2, 'enum', items=(enum('', 2),)),
            field('MSGS', 'MSG-Source', 31, 1, 'enum', items=(enum('RLT-Master', 0),)),
        ), conditions=(cond('data', 29, 2, 2), cond('data', 31, 1, 0))),
        case((
            LRNB_4BS,
            field('STCNT', 'Sub-Telegram Counter', 0, 2, 'enum', items=(enum('not supported', 0),)),
            field('RSLV', 'RSSI Level in dBm', 2, 6, 'enum', items=(enum('not supported', 0), enum('≥-31', 1, unit='dBm'), enum('-32', 2, unit='dBm'), enum('≤-93', 63, unit='dBm'))),
            field('RSLV', 'Sub-Telegram Counter/RSSI Level in dBm', 8, 8, 'enum', items=(enum('See prev'),)),
            field('RSLV', 'Sub-Telegram Counter/RSSI Level in dBm', 16, 8, 'enum', items=(enum('See prev'),)),
            field('RSLV', 'RSSI Level in dBm', 24, 4, 'enum', items=(enum('not supported', 0), enum('≥ -31', 1, unit='dBm'), enum('-32...-37', 2, unit='dBm'), enum('-38...-43', 3, unit='dBm'), enum('-44...-49', 4, unit='dBm'), enum('-50...-55', 5, unit='dBm'), enum('-56...-61', 6, unit='dBm'), enum('-62...-67', 7, unit='dBm'), enum('-68...-73', 8, unit='dBm'), enum('-74...-79', 9, unit='dBm'), enum('-80...-85', 10, unit='dBm'), enum('≤ -92', 11, unit='dBm'))),
            field('MSGID', 'MSG_ID', 29, 2, 'enum', items=(enum('', 2),)),
            field('MSGS', 'MSG-Source', 31, 1, 'enum', items=(enum('RLT-Slave', 1),)),
        ), conditions=(cond('data', 29, 2, 2), cond('data', 31, 1, 1))),
        case((
            field('LRNB', 'LRN Bit', 4, 1, 'enum', items=(enum('Teach-in telegram', 0), enum('Data telegram', 1))),
            field('MC-MSB', 'RLT MSG-Counter MSB', 0, 4, 'enum', items=(enum(''),)),
            field('MC-LSB', 'RLT MSG-Counter LSB', 5, 2, 'enum', items=(enum(''),)),
            field('MSGS', 'MSG-Source', 7, 1, 'enum', items=(enum('RLT Master', 0),)),
        ), conditions=(cond('data', 31, 1, 0),)),
        case((
            field('LRNB', 'LRN Bit', 4, 1, 'enum', items=(enum('Teach-in telegram', 0), enum('Data telegram', 1))),
            field('MC-MSB', 'RLT MSG-Counter MSB', 0, 4, 'enum', items=(enum(''),)),
            field('MC-LSB', 'RLT MSG-Counter LSB', 5, 2, 'enum', items=(enum(''),)),
            field('MSGS', 'MSG-Source', 7, 1, 'enum', items=(enum('RLT-Slave', 1),)),
        ), conditions=(cond('data', 31, 1, 1),)),
    ),
    (0xa5, 0x3f, 0x7f): profile(0xa5, 0x3f, 0x7f, 'Universal',
        case((
            field('DB3', 'Data Byte 3', 0, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('DB2', 'Data Byte 2', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('DB1', 'Data Byte 1', 16, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('DB0', 'Data Byte 0', 24, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
        )),
    ),
}
