"""EEP profile fragment: A5-10 room operating panels.

Merged into the full PROFILES by the package __init__. Built with the _build helpers;
checked by tests/protocol/test_profiles.py.
"""

# ruff: noqa
from enocean2mqtt.protocol.profiles._build import case, enum, field, profile

PROFILES = {
    (0xa5, 0x10, 0x01): profile(0xa5, 0x10, 0x01, 'Temperature Sensor, Set Point, Fan Speed and Occupancy',
        case((
            field('FAN', 'Fan Speed', 0, 8, 'enum', items=(enum('Auto', minimum=210, maximum=255), enum('Speed 0 (slow)', minimum=190, maximum=209), enum('Speed 1', minimum=165, maximum=189), enum('Speed 2', minimum=145, maximum=164), enum('Speed 3 (fast)', minimum=0, maximum=144))),
            field('SP', 'Set Point (linear)', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x02): profile(0xa5, 0x10, 0x02, 'Temperature Sensor, Set Point, Fan Speed and Day/Night',
        case((
            field('FAN', 'Fan Speed', 0, 8, 'enum', items=(enum('Auto', minimum=210, maximum=255), enum('Speed 0 (slow)', minimum=190, maximum=209), enum('Speed 1', minimum=165, maximum=189), enum('Speed 2', minimum=145, maximum=164), enum('Speed 3 (fast)', minimum=0, maximum=144))),
            field('SP', 'Set Point (linear)', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('SLSW', 'Slide switch', 31, 1, 'enum', items=(enum('Position I / Night / Off', 0), enum('Position O / Day / On', 1))),
        )),
    ),
    (0xa5, 0x10, 0x03): profile(0xa5, 0x10, 0x03, 'Temperature Sensor and Set Point',
        case((
            field('SP', 'Set Point (linear)', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
        )),
    ),
    (0xa5, 0x10, 0x04): profile(0xa5, 0x10, 0x04, 'Temperature Sensor, Set Point and Fan Speed',
        case((
            field('FAN', 'Fan Speed', 0, 8, 'enum', items=(enum('Auto', minimum=210, maximum=255), enum('Speed 0 (slow)', minimum=190, maximum=209), enum('Speed 1', minimum=165, maximum=189), enum('Speed 2', minimum=145, maximum=164), enum('Speed 3 (fast)', minimum=0, maximum=144))),
            field('SP', 'Set Point (linear)', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
        )),
    ),
    (0xa5, 0x10, 0x05): profile(0xa5, 0x10, 0x05, 'Temperature Sensor, Set Point and Occupancy Control',
        case((
            field('SP', 'Set Point (linear)', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x06): profile(0xa5, 0x10, 0x06, 'Temperature Sensor, Set Point and Day/Night Control',
        case((
            field('SP', 'Set Point (linear)', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('SLSW', 'Slide switch', 31, 1, 'enum', items=(enum('Position I / Night / Off', 0), enum('Position O / Day / On', 1))),
        )),
    ),
    (0xa5, 0x10, 0x07): profile(0xa5, 0x10, 0x07, 'Temperature Sensor and Fan Speed',
        case((
            field('FAN', 'Fan Speed', 0, 8, 'enum', items=(enum('Auto', minimum=210, maximum=255), enum('Speed 0 (slow)', minimum=190, maximum=209), enum('Speed 1', minimum=165, maximum=189), enum('Speed 2', minimum=145, maximum=164), enum('Speed 3 (fast)', minimum=0, maximum=144))),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
        )),
    ),
    (0xa5, 0x10, 0x08): profile(0xa5, 0x10, 0x08, 'Temperature Sensor, Fan Speed and Occupancy',
        case((
            field('FAN', 'Fan Speed', 0, 8, 'enum', items=(enum('Auto', minimum=210, maximum=255), enum('Speed 0 (slow)', minimum=190, maximum=209), enum('Speed 1', minimum=165, maximum=189), enum('Speed 2', minimum=145, maximum=164), enum('Speed 3 (fast)', minimum=0, maximum=144))),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x09): profile(0xa5, 0x10, 0x09, 'Temperature Sensor, Fan Speed and Day/Night',
        case((
            field('FAN', 'Fan Speed', 0, 8, 'enum', items=(enum('Auto', minimum=210, maximum=255), enum('Speed 0 (slow)', minimum=190, maximum=209), enum('Speed 1', minimum=165, maximum=189), enum('Speed 2', minimum=145, maximum=164), enum('Speed 3 (fast)', minimum=0, maximum=144))),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('SLSW', 'Slide switch', 31, 1, 'enum', items=(enum('Position I / Night / Off', 0), enum('Position O / Day / On', 1))),
        )),
    ),
    (0xa5, 0x10, 0x0a): profile(0xa5, 0x10, 0x0a, 'Temperature Sensor, Set Point and Single Input Contact',
        case((
            field('SP', 'Set Point (linear)', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('CTST', 'Contact State', 31, 1, 'enum', items=(enum('closed', 0), enum('open', 1))),
        )),
    ),
    (0xa5, 0x10, 0x0b): profile(0xa5, 0x10, 0x0b, 'Temperature Sensor and Single Input Contact',
        case((
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('CTST', 'Contact State', 31, 1, 'enum', items=(enum('closed', 0), enum('open', 1))),
        )),
    ),
    (0xa5, 0x10, 0x0c): profile(0xa5, 0x10, 0x0c, 'Temperature Sensor and Occupancy',
        case((
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x0d): profile(0xa5, 0x10, 0x0d, 'Temperature Sensor and Day/Night',
        case((
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('SLSW', 'Slide switch', 31, 1, 'enum', items=(enum('Position I / Night / Off', 0), enum('Position O / Day / On', 1))),
        )),
    ),
    (0xa5, 0x10, 0x10): profile(0xa5, 0x10, 0x10, 'Temperature and Humidity Sensor, Set Point and Occupancy Control',
        case((
            field('SP', 'Set Point (linear)', 0, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x11): profile(0xa5, 0x10, 0x11, 'Temperature and Humidity Sensor, Set Point and Day/Night',
        case((
            field('SP', 'Set Point (linear)', 0, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('SLSW', 'Slide switch', 31, 1, 'enum', items=(enum('Position I / Night / Off', 0), enum('Position O / Day / On', 1))),
        )),
    ),
    (0xa5, 0x10, 0x12): profile(0xa5, 0x10, 0x12, 'Temperature and Humidity Sensor and Set Point',
        case((
            field('SP', 'Set Point (linear)', 0, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
        )),
    ),
    (0xa5, 0x10, 0x13): profile(0xa5, 0x10, 0x13, 'Temperature and Humidity Sensor and Occupancy',
        case((
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x14): profile(0xa5, 0x10, 0x14, 'Temperature and Humidity Sensor and Day/Night',
        case((
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('SLSW', 'Slide switch', 31, 1, 'enum', items=(enum('Position I / Night / Off', 0), enum('Position O / Day / On', 1))),
        )),
    ),
    (0xa5, 0x10, 0x15): profile(0xa5, 0x10, 0x15, 'Temperature Sensor (10 bit) and Set Point',
        case((
            field('SP', 'Set Point (linear)', 8, 6, 'value', range_min=0.0, range_max=63.0, scale_min=0.0, scale_max=63.0),
            field('TMP', 'Temperature (linear)', 14, 10, 'value', unit='°C', range_min=1023.0, range_max=0.0, scale_min=-10.0, scale_max=41.2),
        )),
    ),
    (0xa5, 0x10, 0x16): profile(0xa5, 0x10, 0x16, 'Temperature Sensor (10 bit), Set Point and Occupancy',
        case((
            field('SP', 'Set Point (linear)', 8, 6, 'value', range_min=0.0, range_max=63.0, scale_min=0.0, scale_max=63.0),
            field('TMP', 'Temperature (linear)', 14, 10, 'value', unit='°C', range_min=1023.0, range_max=0.0, scale_min=-10.0, scale_max=41.2),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x17): profile(0xa5, 0x10, 0x17, 'Temperature Sensor (10 bit) and Occupancy',
        case((
            field('TMP', 'Temperature (linear)', 14, 10, 'value', unit='°C', range_min=1023.0, range_max=0.0, scale_min=-10.0, scale_max=41.2),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x18): profile(0xa5, 0x10, 0x18, 'Temperature Sensor, Illumination, Set Point, Fan and Occupancy',
        case((
            field('ILL', 'Illumination (linear)', 0, 8, 'value', unit='lx', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=1000.0),
            field('TMPSP', 'Temperature Set Point (linear)', 8, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 25, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
            field('OED', 'Occupancy Enable/Disable', 30, 1, 'enum', items=(enum('enabled', 0), enum('disabled', 1))),
            field('OB', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x19): profile(0xa5, 0x10, 0x19, 'Temperature and Humidity Sensor, Set Point, Fan and Occupancy',
        case((
            field('HUM', 'Rel. Humidity (linear)', 0, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMPSP', 'Temperature Set Point (linear)', 8, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 25, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
            field('OB', 'Occupancy Button', 30, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
            field('OED', 'Occupancy Enable/Disable', 31, 1, 'enum', items=(enum('enabled', 0), enum('disabled', 1))),
        )),
    ),
    (0xa5, 0x10, 0x1a): profile(0xa5, 0x10, 0x1a, 'Temperature Sensor, Supply Voltage, Set Point, Fan and Occupancy',
        case((
            field('SV', 'Supply voltage (linear)', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('TMPSP', 'Temperature Set Point (linear)', 8, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 25, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
            field('OED', 'Occupancy Enable/Disable', 30, 1, 'enum', items=(enum('enabled', 0), enum('disabled', 1))),
            field('OB', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x1b): profile(0xa5, 0x10, 0x1b, 'Temperature Sensor, Illumination, Supply Voltage, Fan and Occupancy',
        case((
            field('SV', 'Supply voltage (linear)', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('ILL', 'Illumination (linear)', 8, 8, 'value', unit='lx', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=1000.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 25, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
            field('OED', 'Occupancy Enable/Disable', 30, 1, 'enum', items=(enum('enabled', 0), enum('disabled', 1))),
            field('OB', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x1c): profile(0xa5, 0x10, 0x1c, 'Temperature Sensor, Illumination and Set Point, Fan and Occupancy',
        case((
            field('ILL', 'Illumination (linear)', 0, 8, 'value', unit='lx', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=1000.0),
            field('ILLSP', 'Illumination Set Point (linear)', 8, 8, 'value', unit='lx', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=1000.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 25, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
            field('OED', 'Occupancy Enable/Disable', 30, 1, 'enum', items=(enum('enabled', 0), enum('disabled', 1))),
            field('OB', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x1d): profile(0xa5, 0x10, 0x1d, 'Temperature and Humidity Sensor and Set Point, Fan and Occupancy',
        case((
            field('HUM', 'Rel. Humidity (linear)', 0, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('HUMSP', 'Humidity Set Point (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 25, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
            field('OED', 'Occupancy Enable/Disable', 30, 1, 'enum', items=(enum('enabled', 0), enum('disabled', 1))),
            field('OB', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x1e): profile(0xa5, 0x10, 0x1e, 'Temperature Sensor, Illumination, Supply Voltage, Fan and Occupancy (as -1B)',
        case((
            field('SV', 'Supply voltage (linear)', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('ILL', 'Illumination (linear)', 8, 8, 'value', unit='lx', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=1000.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=250.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 25, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
            field('OED', 'Occupancy Enable/Disable', 30, 1, 'enum', items=(enum('enabled', 0), enum('disabled', 1))),
            field('OB', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x1f): profile(0xa5, 0x10, 0x1f, 'Temperature Sensor, Set Point, Fan Speed and Occupancy (with validity flags)',
        case((
            field('FAN', 'Fan Speed', 0, 8, 'enum', items=(enum('Auto', minimum=210, maximum=255), enum('Speed 0 (slow)', minimum=190, maximum=209), enum('Speed 1', minimum=165, maximum=189), enum('Speed 2', minimum=145, maximum=164), enum('Speed 3 (fast)', minimum=0, maximum=144))),
            field('SP', 'Set Point (linear)', 8, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('TMPF', 'Temperature valid', 25, 1, 'bool'),
            field('SPF', 'Set Point valid', 26, 1, 'bool'),
            field('FANF', 'Fan Speed valid', 27, 1, 'bool'),
            field('UNOCC', 'Unoccupancy', 30, 1, 'bool'),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x10, 0x20): profile(0xa5, 0x10, 0x20, 'Temperature Sensor, Set Point, Set Point Mode and Battery',
        case((
            field('SP', 'Set Point (linear)', 0, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('SPM', 'Set Point Mode', 25, 2, 'enum', items=(enum('room set point', 0), enum('frost protection', 1), enum('automatic', 2), enum('reserved', 3))),
            field('BATT', 'Battery', 27, 1, 'enum', items=(enum('ok', 0), enum('low', 1))),
            field('ACT', 'User Activity', 31, 1, 'enum', items=(enum('no interaction', 0), enum('interaction', 1))),
        )),
    ),
    (0xa5, 0x10, 0x21): profile(0xa5, 0x10, 0x21, 'Temperature and Humidity Sensor, Set Point, Set Point Mode and Battery',
        case((
            field('SP', 'Set Point (linear)', 0, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('SPM', 'Set Point Mode', 25, 2, 'enum', items=(enum('room set point', 0), enum('frost protection', 1), enum('automatic', 2), enum('reserved', 3))),
            field('BATT', 'Battery', 27, 1, 'enum', items=(enum('ok', 0), enum('low', 1))),
            field('ACT', 'User Activity', 31, 1, 'enum', items=(enum('no interaction', 0), enum('interaction', 1))),
        )),
    ),
    (0xa5, 0x10, 0x22): profile(0xa5, 0x10, 0x22, 'Temperature and Humidity Sensor, Set Point and Fan Speed',
        case((
            field('SP', 'Set Point (linear)', 0, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 24, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
        )),
    ),
    (0xa5, 0x10, 0x23): profile(0xa5, 0x10, 0x23, 'Temperature and Humidity Sensor, Set Point, Fan Speed and Occupancy',
        case((
            field('SP', 'Set Point (linear)', 0, 8, 'value', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('FAN', 'Fan Speed', 24, 3, 'enum', items=(enum('Auto', 0), enum('Speed 0', 1), enum('Speed 1', 2), enum('Speed 2', 3), enum('Speed 3', 4), enum('Speed 4', 5), enum('Speed 5', 6), enum('Off', 7))),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
}
