"""EEP profile fragment: A5 (4BS) environmental sensors.

Merged into the full PROFILES by the package __init__. Built with the _build helpers;
checked by tests/protocol/test_profiles.py.
"""

# ruff: noqa
from enocean2mqtt.protocol.profiles._build import LRNB_4BS, case, enum, field, profile

PROFILES = {
    (0xa5, 0x02, 0x01): profile(0xa5, 0x02, 0x01, 'Temperature Sensor Range -40°C to 0°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-40.0, scale_max=0.0),
        )),
    ),
    (0xa5, 0x02, 0x02): profile(0xa5, 0x02, 0x02, 'Temperature Sensor Range -30°C to +10°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-30.0, scale_max=10.0),
        )),
    ),
    (0xa5, 0x02, 0x03): profile(0xa5, 0x02, 0x03, 'Temperature Sensor Range -20°C to +20°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-20.0, scale_max=20.0),
        )),
    ),
    (0xa5, 0x02, 0x04): profile(0xa5, 0x02, 0x04, 'Temperature Sensor Range -10°C to +30°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-10.0, scale_max=30.0),
        )),
    ),
    (0xa5, 0x02, 0x05): profile(0xa5, 0x02, 0x05, 'Temperature Sensor Range 0°C to +40°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
        )),
    ),
    (0xa5, 0x02, 0x06): profile(0xa5, 0x02, 0x06, 'Temperature Sensor Range +10°C to +50°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=10.0, scale_max=50.0),
        )),
    ),
    (0xa5, 0x02, 0x07): profile(0xa5, 0x02, 0x07, 'Temperature Sensor Range +20°C to +60°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=20.0, scale_max=60.0),
        )),
    ),
    (0xa5, 0x02, 0x08): profile(0xa5, 0x02, 0x08, 'Temperature Sensor Range +30°C to +70°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=30.0, scale_max=70.0),
        )),
    ),
    (0xa5, 0x02, 0x09): profile(0xa5, 0x02, 0x09, 'Temperature Sensor Range +40°C to +80°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=40.0, scale_max=80.0),
        )),
    ),
    (0xa5, 0x02, 0x0a): profile(0xa5, 0x02, 0x0a, 'Temperature Sensor Range +50°C to +90°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=50.0, scale_max=90.0),
        )),
    ),
    (0xa5, 0x02, 0x0b): profile(0xa5, 0x02, 0x0b, 'Temperature Sensor Range +60°C to +100°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=60.0, scale_max=100.0),
        )),
    ),
    (0xa5, 0x02, 0x10): profile(0xa5, 0x02, 0x10, 'Temperature Sensor Range -60°C to +20°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-60.0, scale_max=20.0),
        )),
    ),
    (0xa5, 0x02, 0x11): profile(0xa5, 0x02, 0x11, 'Temperature Sensor Range -50°C to +30°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-50.0, scale_max=30.0),
        )),
    ),
    (0xa5, 0x02, 0x12): profile(0xa5, 0x02, 0x12, 'Temperature Sensor Range -40°C to +40°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-40.0, scale_max=40.0),
        )),
    ),
    (0xa5, 0x02, 0x13): profile(0xa5, 0x02, 0x13, 'Temperature Sensor Range -30°C to +50°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-30.0, scale_max=50.0),
        )),
    ),
    (0xa5, 0x02, 0x14): profile(0xa5, 0x02, 0x14, 'Temperature Sensor Range -20°C to +60°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-20.0, scale_max=60.0),
        )),
    ),
    (0xa5, 0x02, 0x15): profile(0xa5, 0x02, 0x15, 'Temperature Sensor Range -10°C to +70°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=-10.0, scale_max=70.0),
        )),
    ),
    (0xa5, 0x02, 0x16): profile(0xa5, 0x02, 0x16, 'Temperature Sensor Range 0°C to +80°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=80.0),
        )),
    ),
    (0xa5, 0x02, 0x17): profile(0xa5, 0x02, 0x17, 'Temperature Sensor Range +10°C to +90°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=10.0, scale_max=90.0),
        )),
    ),
    (0xa5, 0x02, 0x18): profile(0xa5, 0x02, 0x18, 'Temperature Sensor Range +20°C to +100°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=20.0, scale_max=100.0),
        )),
    ),
    (0xa5, 0x02, 0x19): profile(0xa5, 0x02, 0x19, 'Temperature Sensor Range +30°C to +110°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=30.0, scale_max=110.0),
        )),
    ),
    (0xa5, 0x02, 0x1a): profile(0xa5, 0x02, 0x1a, 'Temperature Sensor Range +40°C to +120°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=40.0, scale_max=120.0),
        )),
    ),
    (0xa5, 0x02, 0x1b): profile(0xa5, 0x02, 0x1b, 'Temperature Sensor Range +50°C to +130°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=50.0, scale_max=130.0),
        )),
    ),
    (0xa5, 0x02, 0x20): profile(0xa5, 0x02, 0x20, '10 Bit Temperature Sensor Range -10°C to +41.2°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 14, 10, 'value', unit='°C', range_min=1023.0, range_max=0.0, scale_min=-10.0, scale_max=41.2),
        )),
    ),
    (0xa5, 0x02, 0x30): profile(0xa5, 0x02, 0x30, '10 Bit Temperature Sensor Range -40°C to +62.3°C',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 14, 10, 'value', unit='°C', range_min=1023.0, range_max=0.0, scale_min=-40.0, scale_max=62.3),
        )),
    ),
    (0xa5, 0x04, 0x01): profile(0xa5, 0x04, 0x01, 'Range 0°C to +40°C and 0% to 100%',
        case((
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=40.0),
            field('TSN', 'Availability of the Temperature Sensor', 30, 1, 'enum', items=(enum('not available', 0), enum('available', 1))),
        )),
    ),
    (0xa5, 0x04, 0x02): profile(0xa5, 0x04, 0x02, 'Range -20°C to +60°C and 0% to 100%',
        case((
            field('HUM', 'Rel. Humidity (linear)', 8, 8, 'value', unit='%', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 16, 8, 'value', unit='°C', range_min=0.0, range_max=250.0, scale_min=-20.0, scale_max=60.0),
            field('TSN', 'Availability of the Temperature Sensor', 30, 1, 'enum', items=(enum('not available', 0), enum('available', 1))),
        )),
    ),
    (0xa5, 0x04, 0x03): profile(0xa5, 0x04, 0x03, 'Range -20°C to +60°C 10bit-measurement and 0% to 100%',
        case((
            field('HUM', 'Rel. Humidity (linear)', 0, 8, 'value', unit='%', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 14, 10, 'value', unit='°C', range_min=0.0, range_max=1023.0, scale_min=-20.0, scale_max=60.0),
            field('TTP', 'Telegram Type', 31, 1, 'enum', items=(enum('Heartbeat', 0), enum('Event triggered', 1))),
        )),
    ),
    (0xa5, 0x04, 0x04): profile(0xa5, 0x04, 0x04, 'Range -40°C to +120°C 12bit-measurement and 0% to 100%',
        case((
            field('HUM', 'Rel. Humidity (linear)', 0, 8, 'value', unit='%', range_min=0.0, range_max=199.0, scale_min=0.0, scale_max=100.0),
            field('TMP', 'Temperature (linear)', 12, 12, 'value', unit='°C', range_min=0.0, range_max=1599.0, scale_min=-40.0, scale_max=120.0),
        )),
    ),
    (0xa5, 0x05, 0x01): profile(0xa5, 0x05, 0x01, 'Barometric Sensor, Range 500 to 1150 hPa',
        case((
            field('BAR', 'Barometer (linear)', 6, 10, 'value', unit='hPa', range_min=0.0, range_max=1023.0, scale_min=500.0, scale_max=1150.0),
            field('TTP', 'Telegram Type', 31, 1, 'enum', items=(enum('Heartbeat', 0), enum('Event', 1))),
        )),
    ),
    (0xa5, 0x06, 0x01): profile(0xa5, 0x06, 0x01, 'Range 300lx to 60.000lx',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=5.1),
            field('ILL2', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=300.0, scale_max=30000.0),
            field('ILL1', 'Illumination', 16, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=600.0, scale_max=60000.0),
            field('RS', 'Range select', 31, 1, 'enum', items=(enum('Range acc. to DB_1 (ILL1)', 0), enum('Range acc. to DB_2 (ILL2)', 1))),
        )),
    ),
    (0xa5, 0x06, 0x02): profile(0xa5, 0x06, 0x02, 'Range 0lx to 1.020lx',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=5.1),
            field('ILL2', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=510.0),
            field('ILL1', 'Illumination', 16, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=1020.0),
            field('RS', 'Range select', 31, 1, 'enum', items=(enum('Range acc. to DB_1 (ILL1)', 0), enum('Range acc. to DB_2 (ILL2)', 1))),
        )),
    ),
    (0xa5, 0x06, 0x03): profile(0xa5, 0x06, 0x03, '10-bit measurement (1-Lux resolution) with range 0lx to 1000lx',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('ILL', 'Illumination', 8, 10, 'value', unit='lx', range_min=0.0, range_max=1000.0, scale_min=0.0, scale_max=1000.0),
        )),
    ),
    (0xa5, 0x06, 0x04): profile(0xa5, 0x06, 0x04, 'Curtain Wall Brightness Sensor',
        case((
            LRNB_4BS,
            field('TEMP', 'Temperature', 0, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=-20.0, scale_max=60.0),
            field('ILL', 'Illuminance', 8, 16, 'value', unit='lx', range_min=0.0, range_max=65535.0, scale_min=0.0, scale_max=65535.0),
            field('SV', 'Energy Storage', 24, 4, 'value', unit='%', range_min=0.0, range_max=15.0, scale_min=0.0, scale_max=100.0),
            field('TMPAV', 'Temperature Availability', 30, 1, 'enum', items=(enum('Temperature data is unavailable', 0), enum('Temperature data is available', 1))),
            field('ENAV', 'Energy Storage Availability', 31, 1, 'enum', items=(enum('Energy storage data is unavailable', 0), enum('Energy storage data is available', 1))),
        )),
    ),
    (0xa5, 0x06, 0x05): profile(0xa5, 0x06, 0x05, 'Range 0lx to 10.200lx',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=5.1),
            field('ILL2', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=5100.0),
            field('ILL1', 'Illumination', 16, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=10200.0),
            field('RS', 'Range select', 31, 1, 'enum', items=(enum('Range acc. to DB_1 (ILL1)', 0), enum('Range acc. to DB_2 (ILL2)', 1))),
        )),
    ),
    (0xa5, 0x07, 0x01): profile(0xa5, 0x07, 0x01, 'Occupancy with Supply voltage monitor',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage (OPTIONAL)', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('PIRS', 'PIR Status', 16, 8, 'enum', items=(enum('PIR off', minimum=0, maximum=127), enum('PIR on', minimum=128, maximum=255))),
            field('SVA', 'Supply voltage availability', 31, 1, 'enum', items=(enum('Supply voltage is not supported', 0), enum('Supply voltage is supported', 1))),
        )),
    ),
    (0xa5, 0x07, 0x02): profile(0xa5, 0x07, 0x02, 'Occupancy with Supply voltage monitor',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage (REQUIRED)', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('PIRS', 'PIR Status', 24, 1, 'enum', items=(enum('Uncertain of occupancy status', 0), enum('Motion detected', 1))),
        )),
    ),
    (0xa5, 0x07, 0x03): profile(0xa5, 0x07, 0x03, 'Occupancy with Supply voltage monitor and 10-bit illumination measurement',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage (REQUIRED)', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('ILL', 'Illumination', 8, 10, 'value', unit='lx', range_min=0.0, range_max=1000.0, scale_min=0.0, scale_max=1000.0),
            field('PIRS', 'PIR Status', 24, 1, 'enum', items=(enum('Motion detected', 1), enum('Uncertain of occupancy status', 0))),
        )),
    ),
    (0xa5, 0x08, 0x01): profile(0xa5, 0x08, 0x01, 'Range 0lx to 510lx, 0°C to +51°C and Occupancy Button',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=5.1),
            field('ILL', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=510.0),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=51.0),
            field('PIRS', 'PIR Status', 30, 1, 'enum', items=(enum('PIR on', 0), enum('PIR off', 1))),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x08, 0x02): profile(0xa5, 0x08, 0x02, 'Range 0lx to 1020lx, 0°C to +51°C and Occupancy Button',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=5.1),
            field('ILL', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=1020.0),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=51.0),
            field('PIRS', 'PIR Status', 30, 1, 'enum', items=(enum('PIR on', 0), enum('PIR off', 1))),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x08, 0x03): profile(0xa5, 0x08, 0x03, 'Range 0lx to 1530lx, -30°C to +50°C and Occupancy Button',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=5.1),
            field('ILL', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=1530.0),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=-30.0, scale_max=50.0),
            field('PIRS', 'PIR Status', 30, 1, 'enum', items=(enum('PIR on', 0), enum('PIR off', 1))),
            field('OCC', 'Occupancy Button', 31, 1, 'enum', items=(enum('Button pressed', 0), enum('Button released', 1))),
        )),
    ),
    (0xa5, 0x09, 0x02): profile(0xa5, 0x09, 0x02, 'CO-Sensor 0 ppm to 1020 ppm',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=5.1),
            field('Conc', 'Concentration', 8, 8, 'value', unit='ppm', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=1020.0),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=51.0),
            field('TSN', 'T-Sensor', 30, 1, 'enum', items=(enum('Temperature Sensor not available', 0), enum('Temperature Sensor available', 1))),
        )),
    ),
    (0xa5, 0x09, 0x04): profile(0xa5, 0x09, 0x04, 'CO2 Sensor',
        case((
            LRNB_4BS,
            field('HUM', 'Humidity', 0, 8, 'value', unit='%', range_min=0.0, range_max=200.0, scale_min=0.0, scale_max=100.0),
            field('Conc', 'Concentration', 8, 8, 'value', unit='ppm', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=2550.0),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=51.0),
            field('HSN', 'H-Sensor', 29, 1, 'enum', items=(enum('Humidity Sensor not available', 0), enum('Humidity Sensor available', 1))),
            field('TSN', 'T-Sensor', 30, 1, 'enum', items=(enum('Temperature Sensor not available', 0), enum('Temperature Sensor available', 1))),
        )),
    ),
    (0xa5, 0x09, 0x05): profile(0xa5, 0x09, 0x05, 'VOC Sensor',
        case((
            field('Conc', 'VOC', 0, 16, 'value', unit='ppb', range_min=0.0, range_max=65535.0, scale_min=0.0, scale_max=65535.0),
            field('VOC_ID', 'VOC ID', 16, 8, 'enum', items=(enum('VOCT (total)', 0), enum('Formaldehyde', 1), enum('Benzene', 2), enum('Styrene', 3), enum('Toluene', 4), enum('Tetrachloroethylene', 5), enum('Xylene', 6), enum('n-Hexane', 7), enum('n-Octane', 8), enum('Cyclopentane', 9), enum('Methanol', 10), enum('Ethanol', 11), enum('1-Pentanol', 12), enum('Acetone', 13), enum('ethylene Oxide', 14), enum('Acetaldehyde ue', 15), enum('Acetic Acid', 16), enum('Propionice Acid', 17), enum('Valeric Acid', 18), enum('Butyric Acid', 19), enum('Ammoniac', 20), enum('Hydrogen Sulfide', 22), enum('Dimethylsulfide', 23), enum('2-Butanol (butyl Alcohol)', 24), enum('2-Methylpropanol', 25), enum('Diethyl ether', 26), enum('ozone', 255))),
            LRNB_4BS,
            field('SCM', 'Scale Multiplier', 30, 2, 'enum', items=(enum('0.01', 0), enum('0.1', 1), enum('1', 2), enum('10', 3))),
        )),
    ),
    (0xa5, 0x09, 0x06): profile(0xa5, 0x09, 0x06, 'Radon',
        case((
            field('Act', 'Radon', 0, 10, 'value', unit='Bq/m3', range_min=0.0, range_max=1023.0, scale_min=0.0, scale_max=1023.0),
            LRNB_4BS,
        )),
    ),
    (0xa5, 0x09, 0x07): profile(0xa5, 0x09, 0x07, 'Particles',
        case((
            field('PM10', 'Particles_10', 0, 9, 'value', unit='µg/m3', range_min=0.0, range_max=511.0, scale_min=0.0, scale_max=511.0),
            field('PM2.5', 'Particles_2.5', 9, 9, 'value', unit='µg/m3', range_min=0.0, range_max=511.0, scale_min=0.0, scale_max=511.0),
            field('PM1', 'Particles_1', 18, 9, 'value', unit='µg/m3', range_min=0.0, range_max=511.0, scale_min=0.0, scale_max=511.0),
            LRNB_4BS,
            field('PM10a', 'PM10 active', 29, 1, 'enum', items=(enum('PM10 not active', 0), enum('PM10 active', 1))),
            field('PM2.5a', 'PM2.5 active', 30, 1, 'enum', items=(enum('PM2.5 not active', 0), enum('PM2.5 active', 1))),
            field('PM1a', 'PM1 active', 31, 1, 'enum', items=(enum('PM1 not active', 0), enum('PM1 active', 1))),
        )),
    ),
    (0xa5, 0x09, 0x08): profile(0xa5, 0x09, 0x08, 'Pure CO2 Sensor',
        case((
            field('CO2', 'CO2', 16, 8, 'value', unit='ppm', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=2000.0),
            LRNB_4BS,
        )),
    ),
    (0xa5, 0x09, 0x09): profile(0xa5, 0x09, 0x09, 'Pure CO2 Sensor with Power Failure Detection',
        case((
            field('CO2', 'CO2', 16, 8, 'value', unit='ppm', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=2000.0),
            LRNB_4BS,
            field('PFD', 'Power Failure detection', 29, 1, 'enum', items=(enum('Power failure not detected', 0), enum('Power failure detected', 1))),
        )),
    ),
    (0xa5, 0x09, 0x0a): profile(0xa5, 0x09, 0x0a, 'Hydrogen Gas Sensor',
        case((
            field('Conc', 'Concentration', 0, 16, 'value', unit='ppm', range_min=0.0, range_max=65535.0, scale_min=0.0, scale_max=65535.0),
            field('TEMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=-20.0, scale_max=60.0),
            field('SV', 'Supply voltage', 24, 4, 'value', unit='V', range_min=0.0, range_max=15.0, scale_min=2.0, scale_max=5.0),
            LRNB_4BS,
            field('TSA', 'Temp sensor availability', 30, 1, 'enum', items=(enum('Temp sensor is not supported', 0), enum('Temp sensor is supported', 1))),
            field('SVA', 'Supply voltage availability', 31, 1, 'enum', items=(enum('Supply voltage is not supported', 0), enum('Supply voltage is supported', 1))),
        )),
    ),
    (0xa5, 0x09, 0x0b): profile(0xa5, 0x09, 0x0b, 'Radioactivity Sensor',
        case((
            field('SV', 'Supply voltage', 0, 4, 'value', unit='V', range_min=0.0, range_max=15.0, scale_min=2.0, scale_max=5.0),
            field('Ract', 'Radioactivity', 8, 16, 'value', unit='According to', range_min=0.0, range_max=65535.0, scale_min=0.0, scale_max=6553.0),
            LRNB_4BS,
            field('SCM', 'Scale Multiplier', 24, 4, 'enum', items=(enum('0.001', 0), enum('0.01', 1), enum('0.1', 2), enum('1', 3), enum('10', 4), enum('100', 5), enum('1000', 6), enum('10000', 7), enum('100000', 8))),
            field('VUNIT', 'Value unit', 29, 2, 'enum', items=(enum('μSv/h', 0), enum('cpm', 1), enum('Bq/L', 2), enum('Bq/kg', 3))),
            field('SVA', 'Supply voltage availability', 31, 1, 'enum', items=(enum('Supply voltage is not supported', 0), enum('Supply voltage is supported', 1))),
        )),
    ),
    (0xa5, 0x09, 0x0c): profile(0xa5, 0x09, 0x0c, 'VOC Sensor',
        case((
            LRNB_4BS,
            field('Conc', 'VOC', 0, 16, 'value', range_min=0.0, range_max=65535.0, scale_min=0.0, scale_max=65535.0),
            field('VOC ID', 'VOC ID*', 16, 8, 'enum', items=(enum('VOCT (total)', 0), enum('Formaldehyde', 1), enum('Benzene', 2), enum('Styrene', 3), enum('Toluene', 4), enum('Tetrachloroethylene', 5), enum('Xylene', 6), enum('n-Hexane', 7), enum('n-Octane', 8), enum('Cyclopentane', 9), enum('Methanol', 10), enum('Ethanol', 11), enum('1-Pentanol', 12), enum('Acetone', 13), enum('ethylene Oxide', 14), enum('Acetaldehyde ue', 15), enum('Acetic Acid', 16), enum('Propionice Acid', 17), enum('Valeric Acid', 18), enum('Butyric Acid', 19), enum('Ammoniac', 20), enum('Hydrogen Sulfide', 22), enum('Dimethylsulfide', 23), enum('2-Butanol (butyl Alcohol)', 24), enum('2-Methylpropanol', 25), enum('Diethyl ether', 26), enum('Naphthalene', 27), enum('4-Phenylcyclohexene', 28), enum('Limonene', 29), enum('Trichloroethylene', 30), enum('Isovaleric acid', 31), enum('Indole', 32), enum('Cadaverine', 33), enum('Putrescine', 34), enum('Caproic acid', 35), enum('Ozone', 255))),
            field('Unit', 'Unit', 29, 1, 'enum', items=(enum('ppb', 0), enum('μg/m3', 1))),
            field('SCM', 'Scale Multiplier', 30, 2, 'enum', items=(enum('0.01', 0), enum('0.1', 1), enum('1', 2), enum('10', 3))),
        )),
    ),
    (0xa5, 0x09, 0x0d): profile(0xa5, 0x09, 0x0d, 'VOC, humidity & temperature, Comfort Zone and Indoor Air Quality Indication',
        case((
            field('', 'humidity', 0, 8, 'enum', items=(enum('', minimum=0, maximum=200, scale_min=0.0, scale_max=100.0, unit='%'), enum('Reserved', minimum=201, maximum=255))),
            field('', 'TVOC', 8, 8, 'enum', items=(enum('', minimum=0, maximum=200, scale_min=0.0, scale_max=100.0, unit='%'), enum('Reserved', minimum=201, maximum=255))),
            field('', 'temperature', 16, 8, 'enum', items=(enum('', minimum=0, maximum=250, scale_min=0.0, scale_max=51.0, unit='C'), enum('Reserved', minimum=251, maximum=255))),
            field('', 'CMF-T', 24, 1, 'enum', items=(enum('Temperature out of Comfort Zone', 0), enum('Temperature in Comfort Zone', 1))),
            field('', 'CMF-rh', 25, 1, 'enum', items=(enum('humidity out of Comfort Zone', 0), enum('humidity in Comfort Zone', 1))),
            field('', 'unused', 26, 1, 'enum', items=(enum('always = 1', 1),)),
            field('', 'unused', 27, 1, 'enum', items=(enum('always = 0', 0),)),
            field('', 'LrnBit', 28, 1, 'enum', items=(enum('Teach-in telegram', 0), enum('Data Telegram', 1))),
            field('', 'IAQ', 29, 3, 'enum', items=(enum('excellent Air Quality TVOC = 0...10%', 0), enum('Good Air Quality, TVOC = 10,5....20%', 1), enum('lightly polluted air, TVOC = 20,5....30%', 2), enum('moderately polluted air, TVOC = 30,5...40%', 3), enum('heavily polluted air; TVOC = 40,5...50%', 4), enum('severely polluted air; TVOC = 50,5...70%', 5), enum('extremely polluted air; TVOC > 70%', 6), enum('invalid air quality', 7))),
        )),
    ),
    (0xa5, 0x11, 0x01): profile(0xa5, 0x11, 0x01, 'Lighting Controller',
        case((
            LRNB_4BS,
            field('ILL', 'Illumination', 0, 8, 'value', unit='lx', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=510.0),
            field('ISP', 'Illumination Set Point', 8, 8, 'value', unit='N/A', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('DIM', 'Dimming Output Level', 16, 8, 'value', unit='N/A', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('REP', 'Repeater', 24, 1, 'enum', items=(enum('disabled', 0), enum('enabled', 1))),
            field('PRT', 'Power Relay Timer', 25, 1, 'enum', items=(enum('disabled', 0), enum('enabled', 1))),
            field('DHV', 'Daylight Harvesting', 26, 1, 'enum', items=(enum('disabled', 0), enum('enabled', 1))),
            field('EDIM', 'Dimming', 27, 1, 'enum', items=(enum('switching load', 0), enum('dimming load', 1))),
            field('MGC', 'Magnet Contact', 29, 1, 'enum', items=(enum('open', 0), enum('closed', 1))),
            field('OCC', 'Occupancy', 30, 1, 'enum', items=(enum('unoccupied', 0), enum('occupied', 1))),
            field('PWR', 'Power Relay', 31, 1, 'enum', items=(enum('off', 0), enum('on', 1))),
        )),
    ),
    (0xa5, 0x11, 0x02): profile(0xa5, 0x11, 0x02, 'Temperature Controller Output',
        case((
            LRNB_4BS,
            field('CVAR', 'Control Variable', 0, 8, 'value', unit='%', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=100.0),
            field('FAN', 'FanStage', 8, 8, 'enum', items=(enum('Stage 0 Manual', 0), enum('Stage 1 Manual', 1), enum('Stage 2 Manual', 2), enum('Stage 3 Manual', 3), enum('Stage 0 Automatic', 16), enum('Stage 1 Automatic', 17), enum('Stage 2 Automatic', 18), enum('Stage 3 Automatic', 19), enum('Not Available', 255))),
            field('ASP', 'Actual Setpoint', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=51.2),
            field('ALR', 'Alarm', 24, 1, 'enum', items=(enum('No alarm', 0), enum('Alarm', 1))),
            field('CTM', 'Controller mode', 25, 2, 'enum', items=(enum('Heating', 1), enum('Cooling', 2), enum('Off', 3))),
            field('CST', 'Controller state', 27, 1, 'enum', items=(enum('Automatic', 0), enum('Override', 1))),
            field('ERH', 'Energy hold-off', 29, 1, 'enum', items=(enum('Normal', 0), enum('Energy hold-off/ Dew point', 1))),
            field('RO', 'Room occupancy', 30, 2, 'enum', items=(enum('Occupied', 0), enum('Unoccupied', 1), enum('StandBy', 2), enum('Frost', 3))),
        )),
    ),
    (0xa5, 0x11, 0x03): profile(0xa5, 0x11, 0x03, 'Blind Status',
        case((
            LRNB_4BS,
            field('BSP', 'Blind/shutter pos.', 0, 8, 'value', unit='%', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('AS', 'Angle sign', 8, 1, 'enum', items=(enum('Positive sign', 0), enum('Negative sign', 1))),
            field('AN', 'Angle', 9, 7, 'value', unit='°', range_min=0.0, range_max=90.0, scale_min=0.0, scale_max=180.0),
            field('PVF', 'Position value flag', 16, 1, 'enum', items=(enum('No Position value available', 0), enum('Position value available', 1))),
            field('AVF', 'Angle value flag', 17, 1, 'enum', items=(enum('No Angle value available', 0), enum('Angle value available', 1))),
            field('ES', 'Error state', 18, 2, 'enum', items=(enum('No error present', 0), enum('End-positions are not configured', 1), enum('Internal failure', 2), enum('Not used', 3))),
            field('EP', 'End-position', 20, 2, 'enum', items=(enum('No End-position available', 0), enum('No End-position reached', 1), enum('Blind fully open', 2), enum('Blind fully closed', 3))),
            field('ST', 'Status', 22, 2, 'enum', items=(enum('No Status available', 0), enum('Blind is stopped', 1), enum('Blind opens', 2), enum('Blind closes', 3))),
            field('SM', 'Service Mode', 24, 1, 'enum', items=(enum('Normal mode', 0), enum('Service mode is activated (For example for maintenance)', 1))),
            field('MOTP', 'Mode of the position', 25, 1, 'enum', items=(enum('Normal mode:', 0), enum('Inverse mode:', 1))),
        )),
    ),
    (0xa5, 0x11, 0x04): profile(0xa5, 0x11, 0x04, 'Extended Lighting Status',
        case((
            LRNB_4BS,
            field('P1', 'Parameter 1', 0, 8, 'enum', items=(enum('Mode 0: Dimm-Value (0 .. 255)'),)),
            field('P2', 'Parameter 2', 8, 8, 'enum', items=(enum('Mode 0: Lamp operating hours (MSB 15 .. 8)'),)),
            field('P3', 'Parameter 3', 16, 8, 'enum', items=(enum('Mode 0: Lamp operating hours (7 .. 0 LSB)'),)),
            field('SM', 'Service Mode', 24, 1, 'enum', items=(enum('Normal mode', 0), enum('Service mode is activated.', 1))),
            field('OHF', 'Operating hours flag', 25, 1, 'enum', items=(enum('No lamp operating hours available', 0), enum('Lamp operating hours available', 1))),
            field('ES', 'Error state', 26, 2, 'enum', items=(enum('No error present', 0), enum('Lamp-failure', 1), enum('Internal failure', 2), enum('Failure on the external periphery', 3))),
            field('PM', 'Parameter Mode', 29, 2, 'enum', items=(enum('8 Bit Dimmer Value and Lamp operating hours', 0), enum('RGB Value', 1), enum('Energy metering value', 2), enum('Not used', 3))),
            field('ST', 'Status', 31, 1, 'enum', items=(enum('Lighting off', 0), enum('Lighting on', 1))),
        )),
    ),
    (0xa5, 0x11, 0x05): profile(0xa5, 0x11, 0x05, 'Dual-Channel Switch Actuator',
        case((
            LRNB_4BS,
            field('MT', 'Message Type', 31, 1, 'enum', items=(enum('Request', 0),)),
        ), direction=1),
        case((
            LRNB_4BS,
            field('WM', 'Working Mode', 25, 3, 'enum', items=(enum('mode 1', 1),)),
            field('RS', 'Relay Status', 29, 2, 'enum', items=(enum('CH1 off, CH2 off', 0),)),
            field('MT', 'Message Type', 31, 1, 'enum', items=(enum('Status Report', 1),)),
        ), direction=2),
    ),
    (0xa5, 0x12, 0x00): profile(0xa5, 0x12, 0x00, 'Counter',
        case((
            LRNB_4BS,
            field('MR', 'Meter reading', 0, 24, 'value', range_min=0.0, range_max=16777215.0),
            field('CH', 'Measurement channel', 24, 4, 'value', unit='1', range_min=0.0, range_max=15.0, scale_min=0.0, scale_max=15.0),
            field('DT', 'Data type (unit)', 29, 1, 'enum', items=(enum('Cumulative value', 0, unit='1'), enum('Current value', 1, unit='1/s'))),
            field('DIV', 'Divisor (scale)', 30, 2, 'enum', items=(enum('x/1', 0, scale_min=0.0, scale_max=16777215.0), enum('x/10', 1, scale_min=0.0, scale_max=1677721.5), enum('x/100', 2, scale_min=0.0, scale_max=167772.15), enum('x/1000', 3, scale_min=0.0, scale_max=16777.215))),
        )),
    ),
    (0xa5, 0x12, 0x01): profile(0xa5, 0x12, 0x01, 'Electricity',
        case((
            LRNB_4BS,
            field('MR', 'Meter reading', 0, 24, 'value', range_min=0.0, range_max=16777215.0),
            field('TI', 'Tariff info', 24, 4, 'value', unit='1', range_min=0.0, range_max=15.0, scale_min=0.0, scale_max=15.0),
            field('DT', 'Data type (unit)', 29, 1, 'enum', items=(enum('Cumulative value', 0, unit='kWh'), enum('Current value', 1, unit='W'))),
            field('DIV', 'Divisor (scale)', 30, 2, 'enum', items=(enum('x/1', 0, scale_min=0.0, scale_max=16777215.0), enum('x/10', 1, scale_min=0.0, scale_max=1677721.5), enum('x/100', 2, scale_min=0.0, scale_max=167772.15), enum('x/1000', 3, scale_min=0.0, scale_max=16777.215))),
        )),
    ),
    (0xa5, 0x12, 0x02): profile(0xa5, 0x12, 0x02, 'Gas',
        case((
            LRNB_4BS,
            field('MR', 'meter reading', 0, 24, 'value', range_min=0.0, range_max=16777215.0),
            field('TI', 'Tariff info', 24, 4, 'value', unit='1', range_min=0.0, range_max=15.0, scale_min=0.0, scale_max=15.0),
            field('DT', 'data type (unit)', 29, 1, 'enum', items=(enum('Cumulative value', 0, unit='m³'), enum('Current value', 1, unit='liter/s'))),
            field('DIV', 'divisor (scale)', 30, 2, 'enum', items=(enum('x/1', 0, scale_min=0.0, scale_max=16777215.0), enum('x/10', 1, scale_min=0.0, scale_max=1677721.5), enum('x/100', 2, scale_min=0.0, scale_max=167772.15), enum('x/1000', 3, scale_min=0.0, scale_max=16777.215))),
        )),
    ),
    (0xa5, 0x12, 0x03): profile(0xa5, 0x12, 0x03, 'Water',
        case((
            LRNB_4BS,
            field('MR', 'Meter reading', 0, 24, 'value', range_min=0.0, range_max=16777215.0),
            field('TI', 'Tariff info', 24, 4, 'value', unit='1', range_min=0.0, range_max=15.0, scale_min=0.0, scale_max=15.0),
            field('DT', 'Data type (unit)', 29, 1, 'enum', items=(enum('Cumulative value', 0, unit='m³'), enum('Current value', 1, unit='Liter/s'))),
            field('DIV', 'Divisor (scale)', 30, 2, 'enum', items=(enum('x/1', 0, scale_min=0.0, scale_max=16777215.0), enum('x/10', 1, scale_min=0.0, scale_max=1677721.5), enum('x/100', 2, scale_min=0.0, scale_max=167772.15), enum('x/1000', 3, scale_min=0.0, scale_max=16777.215))),
        )),
    ),
    (0xa5, 0x12, 0x04): profile(0xa5, 0x12, 0x04, 'Temperature and Load Sensor',
        case((
            LRNB_4BS,
            field('MR', 'Meter reading', 0, 14, 'value', unit='gram', range_min=0.0, range_max=16383.0, scale_min=0.0, scale_max=16383.0),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=-40.0, scale_max=40.0),
            field('BL', 'Battery Level', 30, 2, 'enum', items=(enum('100-75%', 0), enum('75-50%', 1), enum('50-25%', 2), enum('25-0%', 3))),
        )),
    ),
    (0xa5, 0x12, 0x05): profile(0xa5, 0x12, 0x05, 'Temperature and Container Sensor',
        case((
            LRNB_4BS,
            field('PS0', 'Position Sensor 0', 0, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS1', 'Position Sensor 1', 1, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS2', 'Position Sensor 2', 2, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS3', 'Position Sensor 3', 3, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS4', 'Position Sensor 4', 4, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS5', 'Position Sensor 5', 5, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS6', 'Position Sensor 6', 6, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS7', 'Position Sensor 7', 7, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS8', 'Position Sensor 8', 8, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('PS9', 'Position Sensor 9', 9, 1, 'enum', items=(enum('not possessed', 0), enum('possessed', 1))),
            field('TMP', 'Temperature', 16, 8, 'value', unit='°C', range_min=0.0, range_max=255.0, scale_min=-40.0, scale_max=40.0),
            field('BL', 'Battery Level', 30, 2, 'enum', items=(enum('100-75%', 0), enum('75-50%', 1), enum('50-25%', 2), enum('25-0%', 3))),
        )),
    ),
    (0xa5, 0x12, 0x10): profile(0xa5, 0x12, 0x10, 'Current meter 16 channels',
        case((
            LRNB_4BS,
            field('MR', 'Meter reading', 0, 24, 'value', range_min=0.0, range_max=16777215.0),
            field('CH', 'Measurement channel', 24, 4, 'value', range_min=0.0, range_max=15.0, scale_min=0.0, scale_max=15.0),
            field('DT', 'Data type (unit)', 29, 1, 'enum', items=(enum('Cumulative value', 0, unit='A.h'), enum('Current value', 1, unit='mA'))),
            field('DIV', 'Divisor (scale)', 30, 2, 'enum', items=(enum('x/1', 0, scale_min=0.0, scale_max=16777215.0), enum('x/10', 1, scale_min=0.0, scale_max=1677721.5), enum('x/100', 2, scale_min=0.0, scale_max=167772.15), enum('x/1000', 3, scale_min=0.0, scale_max=16777.215))),
        )),
    ),
    (0xa5, 0x14, 0x01): profile(0xa5, 0x14, 0x01, 'Single Input Contact (Window/Door), Supply voltage monitor',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('CT', 'Contact', 31, 1, 'enum', items=(enum('Contact closed', 0), enum('Contact open', 1))),
        )),
    ),
    (0xa5, 0x14, 0x02): profile(0xa5, 0x14, 0x02, 'Single Input Contact (Window/Door), Supply voltage monitor and Illumination',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('ILL', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=1000.0),
            field('CT', 'Contact', 31, 1, 'enum', items=(enum('Contact closed', 0), enum('Contact open', 1))),
        )),
    ),
    (0xa5, 0x14, 0x03): profile(0xa5, 0x14, 0x03, 'Single Input Contact (Window/Door), Supply voltage monitor and Vibration',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('VIB', 'Vibration', 30, 1, 'enum', items=(enum('No vibration detected', 0), enum('Vibration detected', 1))),
            field('CT', 'Contact', 31, 1, 'enum', items=(enum('Contact closed', 0), enum('Contact open', 1))),
        )),
    ),
    (0xa5, 0x14, 0x04): profile(0xa5, 0x14, 0x04, 'Single Input Contact (Window/Door), Supply voltage monitor, Vibration and Illumination',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('ILL', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=1000.0),
            field('VIB', 'Vibration', 30, 1, 'enum', items=(enum('No vibration detected', 0), enum('Vibration detected', 1))),
            field('CT', 'Contact', 31, 1, 'enum', items=(enum('Contact closed', 0), enum('Contact open', 1))),
        )),
    ),
    (0xa5, 0x14, 0x05): profile(0xa5, 0x14, 0x05, 'Vibration/Tilt, Supply voltage monitor',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('VIB', 'Vibration', 30, 1, 'enum', items=(enum('No vibration detected', 0), enum('Vibration detected', 1))),
        )),
    ),
    (0xa5, 0x14, 0x06): profile(0xa5, 0x14, 0x06, 'Vibration/Tilt, Illumination and Supply voltage monitor',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('ILL', 'Illumination', 8, 8, 'value', unit='lx', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=1000.0),
            field('VIB', 'Vibration', 30, 1, 'enum', items=(enum('No vibration detected', 0), enum('Vibration detected', 1))),
        )),
    ),
    (0xa5, 0x14, 0x07): profile(0xa5, 0x14, 0x07, 'Dual-door-contact with States Open/Closed and Locked/Unlocked, Supply voltage monitor',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('DCT', 'Door Contact', 29, 1, 'enum', items=(enum('Door Closed', 0), enum('Door Open', 1))),
            field('LCT', 'Lock Contact', 30, 1, 'enum', items=(enum('Door Locked', 0), enum('Door Unlocked', 1))),
        )),
    ),
    (0xa5, 0x14, 0x08): profile(0xa5, 0x14, 0x08, 'Dual-door-contact with States Open/Closed and Locked/Unlocked, Supply voltage monitor and Vibration detection',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('DCT', 'Door Contact', 29, 1, 'enum', items=(enum('Door Closed', 0), enum('Door Open', 1))),
            field('LCT', 'Lock Contact', 30, 1, 'enum', items=(enum('Door Locked', 0), enum('Door Unlocked', 1))),
            field('VIB', 'Vibration', 31, 1, 'enum', items=(enum('No vibration detected', 0), enum('Vibration detected', 1))),
        )),
    ),
    (0xa5, 0x14, 0x09): profile(0xa5, 0x14, 0x09, 'Window/Door-Sensor with States Open/Closed/Tilt, Supply voltage monitor',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('CT', 'Contact', 29, 2, 'enum', items=(enum('Closed', 0), enum('Tilt', 1), enum('Reserved', 2), enum('Open', 3))),
        )),
    ),
    (0xa5, 0x14, 0x0a): profile(0xa5, 0x14, 0x0a, 'Window/Door-Sensor with States Open/Closed/Tilt, Supply voltage monitor and Vibration detection',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 0, 8, 'value', unit='V', range_min=0.0, range_max=250.0, scale_min=0.0, scale_max=5.0),
            field('CT', 'Contact', 29, 2, 'enum', items=(enum('Closed', 0), enum('Tilt', 1), enum('Reserved', 2), enum('Open', 3))),
            field('VIB', 'Vibration', 31, 1, 'enum', items=(enum('No vibration detected', 0), enum('Vibration detected', 1))),
        )),
    ),
    (0xa5, 0x30, 0x01): profile(0xa5, 0x30, 0x01, 'Single Input Contact, Battery Monitor',
        case((
            LRNB_4BS,
            field('SVC', 'Supply voltage', 8, 8, 'enum', items=(enum('Battery LOW', minimum=0, maximum=120), enum('Battery OK', minimum=121, maximum=255))),
            field('IPS', 'Input State', 16, 8, 'enum', items=(enum('Contact closed', minimum=0, maximum=195), enum('Contact open', minimum=196, maximum=255))),
        )),
    ),
    (0xa5, 0x30, 0x02): profile(0xa5, 0x30, 0x02, 'Single Input Contact',
        case((
            LRNB_4BS,
            field('IPS', 'Input State', 31, 1, 'enum', items=(enum('Contact closed', 0), enum('Contact open', 1))),
        )),
    ),
    (0xa5, 0x30, 0x03): profile(0xa5, 0x30, 0x03, '4 Digital Inputs, Wake and Temperature',
        case((
            LRNB_4BS,
            field('TMP', 'Temperature', 8, 8, 'value', unit='°C', range_min=255.0, range_max=0.0, scale_min=0.0, scale_max=40.0),
            field('WA0', 'Status of Wake', 19, 1, 'enum', items=(enum('Low', 0), enum('High', 1))),
            field('DI3', 'Digital Input 3', 20, 1, 'enum', items=(enum('Low', 0), enum('High', 1))),
            field('DI2', 'Digital Input 2', 21, 1, 'enum', items=(enum('Low', 0), enum('High', 1))),
            field('DI1', 'Digital Input 1', 22, 1, 'enum', items=(enum('Low', 0), enum('High', 1))),
            field('DI0', 'Digital Input 0', 23, 1, 'enum', items=(enum('Low', 0), enum('High', 1))),
        )),
    ),
    (0xa5, 0x30, 0x04): profile(0xa5, 0x30, 0x04, '3 Digital Inputs, 1 Digital Input 8 Bits',
        case((
            LRNB_4BS,
            field('DV0', 'Digital value-input', 16, 8, 'value', unit='N/A', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('DI2', 'Digital Input 2', 29, 1, 'enum', items=(enum('Low', 0), enum('High', 1))),
            field('DI1', 'Digital Input 1', 30, 1, 'enum', items=(enum('Low', 0), enum('High', 1))),
            field('DI0', 'Digital Input 0', 31, 1, 'enum', items=(enum('Low', 0), enum('High', 1))),
        )),
    ),
    (0xa5, 0x30, 0x05): profile(0xa5, 0x30, 0x05, 'Single Input Contact, Retransmission, Battery Monitor',
        case((
            LRNB_4BS,
            field('VDD', 'Supply voltage', 8, 8, 'value', unit='V', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=3.3),
            field('ST', 'Signal type', 16, 1, 'enum', items=(enum('Normal signal', 0), enum('Heart beat signal', 1))),
            field('IOS', 'Index of Signals', 17, 7, 'enum', items=(enum('Increment a counter by new telegram', minimum=0, maximum=127),)),
        )),
    ),
    (0xa5, 0x30, 0x06): profile(0xa5, 0x30, 0x06, 'Single Alternate Input Contact, Retransmission, Heartbeat',
        case((
            field('', 'contact', 16, 1, 'enum', items=(enum('Open', 0), enum('Close', 1))),
            field('', 'Index', 17, 3, 'value', range_min=0.0, range_max=7.0, scale_min=0.0, scale_max=7.0),
            field('', 'Type', 20, 1, 'enum', items=(enum('Trigger event', 0), enum('Heartbeat', 1))),
            field('', 'Retransmission', 21, 3, 'value', range_min=0.0, range_max=7.0, scale_min=0.0, scale_max=7.0),
            field('', 'LrnBit', 28, 1, 'enum', items=(enum('Teach-in telegram', 0), enum('Data Telegram', 1))),
        )),
    ),
    (0xa5, 0x37, 0x01): profile(0xa5, 0x37, 0x01, 'Demand Response',
        case((
            field('DRL', 'DR Level', 24, 4, 'value', unit='N/A', range_min=0.0, range_max=15.0, scale_min=0.0, scale_max=15.0),
            LRNB_4BS,
            field('TMPD', 'Temporary default', 0, 8, 'value', unit='N/A', range_min=0.0, range_max=255.0, scale_min=0.0, scale_max=255.0),
            field('SPWRU', 'Absolute/relative power usage', 8, 1, 'enum', items=(enum('Absolute power usage. Interpret\nDB_2.BIT_6...DB_2.BIT_0 as a percentage of the\nmaximum power use.', 0), enum('Relative power usage. Interpret\nDB_2.BIT_6...DB_2.BIT_0 as a percentage of the\ncurrent power use.', 1))),
            field('PWRU', 'Power Usage', 9, 7, 'value', unit='N/A', range_min=0.0, range_max=100.0, scale_min=0.0, scale_max=100.0),
            field('TMOS', 'Timeout Setting', 16, 8, 'value', unit='min', range_min=1.0, range_max=255.0, scale_min=15.0, scale_max=3825.0),
            field('RSD', 'Random start delay', 29, 1, 'enum', items=(enum('False', 0), enum('True', 1))),
            field('RED', 'Randomized end delay', 30, 1, 'enum', items=(enum('False', 0), enum('True', 1))),
            field('MPWRU', 'Max/Min Power Usage for Default DR State', 31, 1, 'enum', items=(enum('Minimum Power usage', 0), enum('Maximum Power usage', 1))),
        )),
    ),
}
