"""EEP profile fragment: D2-01 switches, dimmers and metering.

Merged into the full PROFILES by the package __init__. Built with the _build helpers;
checked by tests/protocol/test_profiles.py.
"""

# ruff: noqa
from enocean2mqtt.protocol.profiles._build import case, cond, enum, field, profile

PROFILES = {
    (0xd2, 0x01, 0x00): profile(0xd2, 0x01, 0x00, 'Electronic switch/dimmer, general type (with energy measurement)',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x01): profile(0xd2, 0x01, 0x01, 'Electronic switch with Local Control',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x02): profile(0xd2, 0x01, 0x02, 'Electronic switch/dimmer with local control and energy measurement',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x03): profile(0xd2, 0x01, 0x03, 'Electronic switch, 1 channel',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x04): profile(0xd2, 0x01, 0x04, 'Electronic switch/dimmer with energy measurement',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x05): profile(0xd2, 0x01, 0x05, 'Electronic dimmer with energy measurement',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x06): profile(0xd2, 0x01, 0x06, 'Electronic switch with energy measurement',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x07): profile(0xd2, 0x01, 0x07, 'Electronic switch, 1 channel',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x08): profile(0xd2, 0x01, 0x08, 'Type 0x08',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x09): profile(0xd2, 0x01, 0x09, 'Type 0x09',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x0a): profile(0xd2, 0x01, 0x0a, 'Smart Plug module, no metering capabilities',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x0b): profile(0xd2, 0x01, 0x0b, 'Smart Plug module with Energy Measurement',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x0c): profile(0xd2, 0x01, 0x0c, 'Heating module with Pilotwire command and Energy Measurement',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('PM', 'Pilotwire mode', 13, 3, 'enum', items=(enum('Off', 0), enum('Comfort', 1), enum('Eco', 2), enum('Anti-freeze', 3), enum('Comfort-1', 4), enum('Comfort-2', 5))),
        ), conditions=(cond('data', 4, 4, 8),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
        ), conditions=(cond('data', 4, 4, 9),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('PM', 'Pilotwire mode', 13, 3, 'enum', items=(enum('Off', 0), enum('Comfort', 1), enum('Eco', 2), enum('Anti-freeze', 3), enum('Comfort-1', 4), enum('Comfort-2', 5))),
        ), conditions=(cond('data', 4, 4, 10),)),
    ),
    (0xd2, 0x01, 0x0d): profile(0xd2, 0x01, 0x0d, 'Micro Smart Plug module with 1 channel, no metering capabilities',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x0e): profile(0xd2, 0x01, 0x0e, 'Micro Smart Plug module with 1 channel, and metering capabilities',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x0f): profile(0xd2, 0x01, 0x0f, 'Slot-in Module with 1 channel, no metering capabilities',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x10): profile(0xd2, 0x01, 0x10, 'Electronic switch, 2 channels, with energy measurement',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('RM', 'Report measurement', 8, 1, 'enum', items=(enum('Query only', 0), enum('Query / auto', 1))),
            field('RE', 'Reset measurement', 9, 1, 'enum', items=(enum('Not active', 0), enum('Trigger signal', 1))),
            field('ep', 'Measurement mode', 10, 1, 'enum', items=(enum('Energy', 0), enum('Power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MD_LSB', 'Measurement delta LSB', 16, 4, 'enum', items=(enum('Measurement delta LSB {value}', minimum=0, maximum=15),)),
            field('UN', 'Unit', 21, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('MD_MSB', 'Measurement delta MSB', 24, 8, 'enum', items=(enum('Measurement delta MSB {value}', minimum=0, maximum=255),)),
            field('MAT', 'Max message time', 32, 8, 'enum', items=(enum('Reserved', 0), enum('Max message time {value}', minimum=1, maximum=255))),
            field('MIT', 'Min message time', 40, 8, 'enum', items=(enum('Reserved', 0), enum('Min message time {value}', minimum=1, maximum=255))),
        ), conditions=(cond('data', 4, 4, 5),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('qu', 'Query', 10, 1, 'enum', items=(enum('Query energy', 0), enum('Query power', 1))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 6),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('UN', 'Unit', 8, 3, 'enum', items=(enum('Energy [Ws]', 0), enum('Energy [Wh]', 1), enum('Energy [KWh]', 2), enum('Power [W]', 3), enum('Power [KW]', 4), enum('Not used', minimum=5, maximum=7))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('MV', 'Measurement value', 16, 32, 'enum', items=(enum('Measurement value {value}', minimum=0, maximum=4294967295),)),
        ), conditions=(cond('data', 4, 4, 7),)),
    ),
    (0xd2, 0x01, 0x11): profile(0xd2, 0x01, 0x11, 'Type 0x11 (electronic switch/actuator, 1 channel; e.g. Omnio)',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x12): profile(0xd2, 0x01, 0x12, 'Slot-in Module with 2 channels, no metering capabilities',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x13): profile(0xd2, 0x01, 0x13, 'Electronic switch, 1 channel',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
    (0xd2, 0x01, 0x14): profile(0xd2, 0x01, 0x14, 'Electronic switch, 1 channel',
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('DV', 'Dim value', 8, 3, 'enum', items=(enum('Switch to new output value', 0), enum('Dim to new output level - dim timer 1', 1), enum('Dim to new output level - dim timer 2', 2), enum('Dim to new output level - dim timer 3', 3), enum('Stop dimming', 4))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 1),)),
        case((
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('All output channels supported by the device', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
        ), conditions=(cond('data', 4, 4, 3),)),
        case((
            field('PF', 'Power Failure', 0, 1, 'enum', items=(enum('Power Failure Detection disabled/not supported', 0), enum('Power Failure Detection enabled', 1))),
            field('PFD', 'Power Failure Detection', 1, 1, 'enum', items=(enum('Power Failure not detected/not supported/disabled', 0), enum('Power Failure Detected', 1))),
            field('CMD', 'Command identifier', 4, 4, 'enum', items=(enum('Command ID {value}', minimum=0, maximum=13),)),
            field('OC', 'Over current switch off', 8, 1, 'enum', items=(enum('Over current switch off: ready / not supported', 0), enum('Over current switch off: executed', 1))),
            field('EL', 'Error level', 9, 2, 'enum', items=(enum('Error level 0: hardware OK', 0), enum('Error level 1: hardware warning', 1), enum('Error level 2: hardware failure', 2), enum('Error level not supported', 3))),
            field('IO', 'I/O channel', 11, 5, 'enum', items=(enum('Not applicable, do not use', 30), enum('Input channel (from mains supply)', 31), enum('Output channel {value} (to load)', minimum=0, maximum=29))),
            field('LC', 'Local control', 16, 1, 'enum', items=(enum('Local control disabled / not supported', 0), enum('Local control enabled', 1))),
            field('OV', 'Output value', 17, 7, 'enum', items=(enum('Output value 0% or OFF', 0), enum('output value not valid / not set', 127), enum('Output value {value}% or ON', minimum=1, maximum=100), enum('Not used', minimum=101, maximum=126))),
        ), conditions=(cond('data', 4, 4, 4),)),
    ),
}
