#!/usr/bin/env python3
"""this is the main entry point, which sets up the EnoceanDaemon class"""

import argparse
import copy
import logging
import logging.handlers
import os
import sys
from configparser import ConfigParser

from enocean2mqtt.application.bootstrap import bootstrap
from enocean2mqtt.devices import duplicate_addresses, duplicate_senders, load_devices_yaml

# Size-capped rotating log file: ~8 MB total (2 MB current + 3 rolled backups). Fixed in code so
# `log_level` stays the only user-facing verbosity knob.
_LOG_MAX_BYTES = 2_000_000
_LOG_BACKUP_COUNT = 3

logger = logging.getLogger("enocean2mqtt.cli")

# Maps the `log_level` option to a Python logging level. At 'debug' the per-telegram "received:"
# lines are shown too — handy for finding device addresses.
_LEVELS = {
    "error": logging.ERROR,
    "warning": logging.WARNING,
    "info": logging.INFO,
    "debug": logging.DEBUG,
}

conf = {
    "log_level": "info",
    "config": ["/etc/enocean2mqtt.conf"],
    "logfile": os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "enocean2mqtt.log"),
}


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(argument_default=argparse.SUPPRESS)
    parser.add_argument(
        "--log-level",
        dest="log_level",
        choices=("error", "warning", "info", "debug"),
        help="console/file log level (default: info)",
    )
    parser.add_argument("--logfile", help="set log file location")
    parser.add_argument("config", help="specify config file[s]", nargs="*")
    # parser.add_argument('--version', help='show application version',
    #     action='version', version='%(prog)s ' + VERSION)
    args = vars(parser.parse_args())
    # logging.info('Read arguments: ' + str(args))
    return args


def load_config_file(config_files):
    """load sensor and general configuration from given config files"""
    # extract sensor configuration
    sensors = []
    global_config = {}

    for conf_file in config_files:
        if not os.path.isfile(conf_file):
            logger.warning("Config file %s does not exist, skipping", conf_file)
            continue
        logger.info("Loading config file %s", conf_file)

        # A devices.yaml file contributes sensors only (the [CONFIG] section comes from the
        # generated .conf, which is passed first, so mqtt_prefix is already known here).
        if conf_file.endswith((".yaml", ".yml")):
            mqtt_prefix = global_config.get("mqtt_prefix", "enocean/")
            sensors.extend(load_devices_yaml(conf_file, mqtt_prefix))
            # Remember the devices.yaml path so learn mode can append provisioned devices to it.
            global_config["device_file"] = conf_file
            continue

        # A .conf file contributes the [CONFIG] section (generated by the add-on's run.sh); the
        # device list is a devices.yaml (see the .yaml branch above).
        config_parser = ConfigParser(inline_comment_prefixes=("#", ";"), interpolation=None)
        if not config_parser.read(conf_file):
            logger.error("Cannot read config file: %s", conf_file)
            sys.exit(1)

        for key in config_parser["CONFIG"] if config_parser.has_section("CONFIG") else {}:
            global_config[key] = config_parser["CONFIG"][key]

    logging_global_config = copy.deepcopy(global_config)
    if "mqtt_pwd" in logging_global_config:
        logging_global_config["mqtt_pwd"] = "*****"
    logger.debug("Global config: %s", logging_global_config)

    return sensors, global_config


def setup_logging(log_filename="", log_level=logging.INFO):
    """initialize python logging infrastructure"""
    # create formatter
    log_formatter = logging.Formatter("%(asctime)s %(levelname)s: %(message)s")

    # set root logger to lowest log level
    logging.getLogger().setLevel(log_level)

    # create console and log file handlers and the formatter to the handlers
    log_console = logging.StreamHandler(sys.stdout)
    log_console.setFormatter(log_formatter)
    log_console.setLevel(log_level)
    logging.getLogger().addHandler(log_console)
    if log_filename:
        log_file = logging.handlers.RotatingFileHandler(
            log_filename, maxBytes=_LOG_MAX_BYTES, backupCount=_LOG_BACKUP_COUNT
        )
        log_file.setLevel(log_level)
        log_file.setFormatter(log_formatter)
        logging.getLogger().addHandler(log_file)
        logger.info("Logging to file: %s", log_filename)


def main():
    """entry point if called as an executable"""
    # logging.getLogger().setLevel(logging.DEBUG)
    # Parse command line arguments
    conf.update(parse_args())

    # setup logger
    setup_logging(conf["logfile"], _LEVELS.get(conf["log_level"], logging.INFO))

    # load config file
    sensors, global_config = load_config_file(conf["config"])
    conf.update(global_config)

    # One-line startup banner so a support log immediately shows the effective wiring.
    logger.info(
        "enocean2mqtt starting — transceiver=%s, broker=%s:%s, devices=%d, "
        "overlay=%s, log level=%s",
        conf.get("enocean_port", "?"),
        conf.get("mqtt_host", "?"),
        conf.get("mqtt_port", "?"),
        len(sensors),
        conf.get("overlay") or "none",
        conf["log_level"],
    )

    # Warn about duplicate sender offsets (two actuators reacting to the same command).
    for sender, names in duplicate_senders(sensors).items():
        logger.error("Duplicate sender 0x%08X used by multiple devices: %s", sender, names)

    # Warn about duplicate (address, RORG): only the first such device receives telegrams.
    for (address, _rorg), names in duplicate_addresses(sensors).items():
        logger.warning(
            "Duplicate address 0x%08X shared by devices (only the first is matched): %s",
            address,
            names,
        )

    # Build the wired daemon at the composition root (validates config, selects the overlay).
    try:
        com = bootstrap(conf, sensors)
    except ImportError:
        logger.error("Unable to import Home Assistant overlay")
        return

    # start working
    try:
        com.run()

    # catch all possible exceptions
    except Exception:  # pylint: disable=broad-except,bare-except
        logger.exception("Unhandled error; shutting down")


# check for execution
if __name__ == "__main__":
    main()
