"""Discovery MAPPING fragment: A5 HVAC + gateway control (A5-20 / A5-38 / A5-3F).

Merged into the full MAPPING by the package __init__. Recurring pieces come from _catalog.py,
scaffolding from _builders.py; one-offs are literals. Structural invariants are checked by tests/ha/test_mapping.py.
"""

# ruff: noqa
from enocean2mqtt.homeassistant.mapping._builders import binary, dcfg, entity, sensor, vt
from enocean2mqtt.homeassistant.mapping._catalog import t_raw, temp_c

MAPPING = {
    165: {
        32: {
            1: {
                'device_config': dcfg(direction='1', answer='1'),
                'entities': [
                    sensor('curval', vt('CV'), unit='%', icon='mdi:valve'),
                    binary('SO', '{% if value_json.SO == 1 %}ON{% else %}OFF{% endif %}'),
                    binary('ENIE', '{% if value_json.ENIE == 1 %}ON{% else %}OFF{% endif %}'),
                    binary('ES', '{% if value_json.ES == 1 %}ON{% else %}OFF{% endif %}'),
                    binary('BCAP', '{% if value_json.BCAP == 1 %}OFF{% else %}ON{% endif %}', device_class='battery'),
                    binary('CCO', '{% if value_json.CCO == 1 %}ON{% else %}OFF{% endif %}'),
                    binary('FTS', '{% if value_json.FTS == 1 %}ON{% else %}OFF{% endif %}', device_class='problem'),
                    binary('DWO', '{% if value_json.DWO == 1 %}ON{% else %}OFF{% endif %}', device_class='window'),
                    binary('ACO', '{% if value_json.ACO == 1 %}ON{% else %}OFF{% endif %}', device_class='problem'),
                    t_raw(),
                    temp_c(),
                    entity('number', 'config_valve_position', command_topic='__trash', min='0', max='100', step='1', mode='slider', unit_of_measurement='%', icon='mdi:valve'),
                    entity('number', 'config_t_setpoint', command_topic='__trash', min='0', max='40', step='0.25', mode='slider', unit_of_measurement='°C', icon='mdi:thermometer'),
                    entity('number', 'config_t_RCU', command_topic='__trash', min='0', max='40', step='0.25', mode='slider', unit_of_measurement='°C', icon='mdi:thermometer'),
                    entity('switch', 'config_RIN', command_topic='__trash'),
                    entity('switch', 'config_LFS', command_topic='__trash'),
                    entity('switch', 'config_VO', command_topic='__trash'),
                    entity('switch', 'config_VC', command_topic='__trash'),
                    entity('switch', 'config_SB', command_topic='__trash'),
                    entity('switch', 'config_SPS', command_topic='__trash'),
                    entity('switch', 'config_SPN', command_topic='__trash'),
                    entity('switch', 'config_RCU', command_topic='__trash'),
                    entity('button', 'set_config', command_topic='req', command_template='{% set ns = namespace() %} {% for entity in device_entities(device_id(entity_id)) %}\n  {% if entity is search(\'config_valve_position\',ignorecase=True) %}\n    {% set ns.valve_position = (states(entity)|int(default=0)) %}\n  {% elif entity is search(\'config_t_setpoint\',ignorecase=True) %}\n    {% set ns.temperature_setpoint = ((states(entity)|int(default=0))*255/40)|int %}\n  {% elif entity is search(\'config_t_RCU\',ignorecase=True) %}\n    {% set ns.TMP = (states(entity)|float(default=0.0)) %}\n  {% elif entity is search(\'config_RIN\',ignorecase=True) %}\n    {% set ns.RIN = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_LFS\',ignorecase=True) %}\n    {% set ns.LFS = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_SPS\',ignorecase=True) %}\n    {% set ns.SPS = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_SPN\',ignorecase=True) %}\n    {% set ns.SPN = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_RCU\',ignorecase=True) %}\n    {% set ns.RCU = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_VO\',ignorecase=True) %}\n    {% set ns.VO = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_VC\',ignorecase=True) %}\n    {% set ns.VC = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_SB\',ignorecase=True) %}\n    {% set ns.SB = iif(is_state(entity, "on"), 1, 0) %}\n  {% endif %}\n{% endfor %} {% set ns.SP = iif((ns.SPS == 1), ns.temperature_setpoint, ns.valve_position) %} {"SP":{{ns.SP}},"TMP":{{ns.TMP}},"RIN":{{ns.RIN}},"LFS":{{ns.LFS}},"VO":{{ns.VO}},"VC":{{ns.VC}},"SB":{{ns.SB}},"SPS":{{ns.SPS}},"SPN":{{ns.SPN}},"RCU":{{ns.RCU}}}', icon='mdi:download'),
                ],
            },
            4: {
                'device_config': dcfg(direction='1', answer='1'),
                'entities': [
                    sensor('curval', vt('CP'), unit='%', icon='mdi:valve'),
                    sensor('ft_raw', '{% if value_json.TS == 0 %}\n  {{ value_json.FTS * 60 / 255 + 20 }}\n{% else %}\n  {{ states(entity_id)|int(default=0) }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C', enabled_by_default='false'),
                    sensor('feed_temperature', '{% if value_json.TS == 0 %}\n  {{ (value_json.FTS * 60 / 255 + 20) | round(1) }}\n{% else %}\n  {{ states(entity_id)|int(default=0) }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C'),
                    sensor('st_raw', '{% if value_json.TS == 1 %}\n  {{ value_json.FTS * 20 / 255 + 10 }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C', enabled_by_default='false'),
                    sensor('setpoint_temperature', '{% if value_json.TS == 1 %}\n  {{ (value_json.FTS * 20 / 255 + 10) | round(1) }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C'),
                    sensor('rt_raw', '{% if value_json.FL == 0 %}\n  {{ value_json.TMPFC * 20 / 255 + 10 }}\n{% else %}\n  {{ states(entity_id)|int(default=0) }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C', enabled_by_default='false'),
                    sensor('room_temperature', '{% if value_json.FL == 0 %}\n  {{ (value_json.TMPFC * 20 / 255 + 10) | round(1) }}\n{% else %}\n  {{ states(entity_id)|int(default=0) }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C'),
                    binary('err_meas', '{% if value_json.FL == 1 %}\n  {% if value_json.TMPFC == 17 %}ON{% else %}OFF{% endif %}\n{% else %}\n  {{ states(entity_id) }}\n{% endif %}', device_class='problem'),
                    binary('battery', '{% if value_json.FL == 1 %}\n  {% if value_json.TMPFC == 18 %}ON{% else %}OFF{% endif %}\n{% else %}\n  {{ states(entity_id) }}\n{% endif %}', device_class='battery'),
                    binary('err_frost_prot', '{% if value_json.FL == 1 %}\n  {% if value_json.TMPFC == 20 %}ON{% else %}OFF{% endif %}\n{% else %}\n  {{ states(entity_id) }}\n{% endif %}', device_class='problem'),
                    binary('err_blocked_valve', '{% if value_json.FL == 1 %}\n  {% if value_json.TMPFC == 33 %}ON{% else %}OFF{% endif %}\n{% else %}\n  {{ states(entity_id) }}\n{% endif %}', device_class='problem'),
                    binary('err_endpoint', '{% if value_json.FL == 1 %}\n  {% if value_json.TMPFC == 36 %}ON{% else %}OFF{% endif %}\n{% else %}\n  {{ states(entity_id) }}\n{% endif %}', device_class='problem'),
                    binary('err_novalve', '{% if value_json.FL == 1 %}\n  {% if value_json.TMPFC == 40 %}ON{% else %}OFF{% endif %}\n{% else %}\n  {{ states(entity_id) }}\n{% endif %}', device_class='problem'),
                    binary('failure', '{% if value_json.FL == 1 %}ON{% else %}OFF{% endif %}', device_class='problem'),
                    entity('number', 'config_position', command_topic='__trash', min='0', max='100', step='1', mode='slider', unit_of_measurement='%', icon='mdi:valve'),
                    entity('number', 'config_TSP', command_topic='__trash', min='10', max='30', step='0.25', mode='slider', unit_of_measurement='°C', icon='mdi:thermometer'),
                    entity('switch', 'config_MC', command_topic='__trash'),
                    entity('select', 'config_wakeup_time', options=['0 - 10 sec', '1 - 60 sec', '2 - 90 sec', '3 - 120 sec', '4 - 150 sec', '5 - 180 sec', '6 - 210 sec', '7 - 240 sec', '8 - 270 sec', '9 - 300 sec', '10 - 330 sec', '11 - 360 sec', '12 - 390 sec', '13 - 420 sec', '14 - 450 sec', '15 - 480 sec', '16 - 510 sec', '17 - 540 sec', '18 - 570 sec', '19 - 600 sec', '20 - 630 sec', '21 - 660 sec', '22 - 690 sec', '23 - 720 sec', '24 - 750 sec', '25 - 780 sec', '26 - 810 sec', '27 - 840 sec', '28 - 870 sec', '29 - 900 sec', '30 - 930 sec', '31 - 960 sec', '32 - 990 sec', '33 - 1020 sec', '34 - 1050 sec', '35 - 1080 sec', '36 - 1110 sec', '37 - 1140 sec', '38 - 1170 sec', '39 - 1200 sec', '40 - 1230 sec', '41 - 1260 sec', '42 - 1290 sec', '43 - 1320 sec', '44 - 1350 sec', '45 - 1380 sec', '46 - 1410 sec', '47 - 1440 sec', '48 - 1470 sec', '49 - 1500 sec', '50 - 3 hrs', '51 - 6 hrs', '52 - 9 hrs', '53 - 12 hrs', '54 - 15 hrs', '55 - 18 hrs', '56 - 21 hrs', '57 - 24 hrs', '58 - 27 hrs', '59 - 30 hrs', '60 - 33 hrs', '61 - 36 hrs', '62 - 39 hrs', '63 - 42 hrs (max)'], command_topic='__trash'),
                    entity('select', 'config_DSO', options=['0°', '90°', '180°', '270°'], command_topic='__trash'),
                    entity('switch', 'config_BLC', command_topic='__trash'),
                    entity('select', 'config_SER', options=['0 - No change', '1 - Open valve', '2 - Run initialization', '3 - Close valve'], command_topic='__trash'),
                    entity('button', 'set_config', command_topic='req', command_template='{% set ns = namespace() %} {% for entity in device_entities(device_id(entity_id)) %}\n  {% if entity is search(\'config_position\',ignorecase=True) %}\n    {% set ns.POS = (states(entity)|int(default=0)) %}\n  {% elif entity is search(\'config_TSP\',ignorecase=True) %}\n    {% set ns.TSP = (states(entity)|float(default=0.0)) %}\n  {% elif entity is search(\'config_wakeup_time\',ignorecase=True) %}\n    {% set ns.WUC = states(entity).split("-")[0]|int(default=0) %}\n  {% elif entity is search(\'config_DSO\',ignorecase=True) %}\n    {% set ns.DSO = (states(entity).split("°")[0]|int(default=0)/90) %}\n  {% elif entity is search(\'config_BLC\',ignorecase=True) %}\n    {% set ns.BLC = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_SER\',ignorecase=True) %}\n    {% set ns.SER = states(entity).split("-")[0]|int(default=0) %}\n  {% elif entity is search(\'config_MC\',ignorecase=True) %}\n    {% set ns.MC = iif(is_state(entity, "on"), 1, 0) %}\n  {% endif %}\n{% endfor %} {"POS":{{ns.POS}},"TSP":{{ns.TSP}},"MC":{{ns.MC}},"WUC":{{ns.WUC}},"DSO":{{ns.DSO}},"BLC":{{ns.BLC}},"SER":{{ns.SER}}}', icon='mdi:download'),
                ],
            },
            6: {
                'device_config': dcfg(direction='1', answer='1'),
                'entities': [
                    sensor('curval', vt('CV'), unit='%', icon='mdi:valve'),
                    sensor('feed_temperature', '{% if value_json.TSL == 1 %}\n  {{ ((value_json.TMP|float(default=0))*0.5) | round(1) }}\n{% else %}\n  {{ states(entity_id)|int(default=0) }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C'),
                    sensor('setpoint_temperature', '{% if value_json.LOM == 1 %}\n  {{ ((value_json.LO|float(default=0))*0.5) | round(1) }}\n{% else %}\n  {{ states(entity_id)|int(default=0) }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C'),
                    sensor('local_offset', '{% if value_json.LOM == 0 %}\n  {% if value_json.LO|int(default=0) > 63 %}\n    {{ ((value_json.LO|int(default=0)-128)) }}\n  {% else %}\n    {{ value_json.LO|int(default=0) }}\n  {% endif %}\n{% else %}\n  {{ states(entity_id)|int(default=0) }}\n{% endif %}', device_class='temperature', unit='°C'),
                    sensor('room_temperature', '{% if value_json.TSL == 0 %}\n  {{ ((value_json.TMP|float(default=0))*0.5) | round(1) }}\n{% else %}\n  {{ states(entity_id)|int(default=0) }}\n{% endif %}', device_class='temperature', state_class='measurement', unit='°C'),
                    binary('LOM', '{% if value_json.LOM == 1 %}ON{% else %}OFF{% endif %}'),
                    binary('TSL', '{% if value_json.TSL == 1 %}ON{% else %}OFF{% endif %}'),
                    binary('ENIE', '{% if value_json.ENIE == 1 %}ON{% else %}OFF{% endif %}'),
                    binary('ES', '{% if value_json.ES == 1 %}OFF{% else %}ON{% endif %}', device_class='battery'),
                    binary('DWO', '{% if value_json.DWO == 1 %}ON{% else %}OFF{% endif %}', device_class='window'),
                    binary('RCE', '{% if value_json.RCE == 1 %}ON{% else %}OFF{% endif %}', device_class='problem'),
                    binary('RSS', '{% if value_json.RSS == 1 %}ON{% else %}OFF{% endif %}', device_class='problem'),
                    binary('ACO', '{% if value_json.ACO == 1 %}ON{% else %}OFF{% endif %}', device_class='problem'),
                    entity('number', 'config_valve_position', command_topic='__trash', min='0', max='100', step='1', mode='slider', unit_of_measurement='%', icon='mdi:valve'),
                    entity('number', 'config_temperature_setpoint', command_topic='__trash', min='0', max='40', step='0.5', mode='slider', unit_of_measurement='°C', icon='mdi:thermometer'),
                    entity('number', 'config_temperature_RCU', command_topic='__trash', min='0', max='40', step='0.25', mode='slider', unit_of_measurement='°C', icon='mdi:thermometer'),
                    entity('switch', 'config_REF', command_topic='__trash'),
                    entity('select', 'config_RFC', options=['AUTO (default) 2, 5 or 10 minutes', '2 minutes', '5 minutes', '10 minutes', '20 minutes', '30 minutes', '60 minutes', '120 minutes'], command_topic='__trash'),
                    entity('switch', 'config_SB', command_topic='__trash'),
                    entity('switch', 'config_SPS', command_topic='__trash'),
                    entity('switch', 'config_TSL', command_topic='__trash'),
                    entity('switch', 'config_SBY', command_topic='__trash'),
                    entity('button', 'set_config', command_topic='req', command_template='{% set ns = namespace() %} {% for entity in device_entities(device_id(entity_id)) %}\n  {% if entity is search(\'config_valve_position\',ignorecase=True) %}\n    {% set ns.valve_position = (states(entity)|int(default=0)) %}\n  {% elif entity is search(\'config_temperature_setpoint\',ignorecase=True) %}\n    {% set ns.temperature_setpoint = ((states(entity)|int(default=0))*2) %}\n  {% elif entity is search(\'config_temperature_RCU\',ignorecase=True) %}\n    {% set ns.TMP = ((states(entity)|float(default=0.0))) %}\n  {% elif entity is search(\'config_REF\',ignorecase=True) %}\n    {% set ns.REF = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_RFC\',ignorecase=True) %}\n    {% set map = {"0": 0, "2": 1, "5": 2, "10": 3, "20": 4, "30": 5, "60": 6, "120": 7} %}\n    {% set ns.RFC = map[states(entity).split(" ")[0]|int(default=0)|string] %}\n  {% elif entity is search(\'config_SBY\',ignorecase=True) %}\n    {% set ns.SBY = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_SPS\',ignorecase=True) %}\n    {% set ns.SPS = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_TSL\',ignorecase=True) %}\n    {% set ns.TSL = iif(is_state(entity, "on"), 1, 0) %}\n  {% elif entity is search(\'config_SB\',ignorecase=True) %}\n    {% set ns.SB = iif(is_state(entity, "on"), 1, 0) %}\n  {% endif %}\n{% endfor %} {% set ns.SP = iif((ns.SPS == 1), ns.temperature_setpoint, ns.valve_position) %} {"SP":{{ns.SP}},"TMP":{{ns.TMP}},"REF":{{ns.REF}},"RFC":{{ns.RFC}},"SB":{{ns.SB}},"SPS":{{ns.SPS}},"TSL":{{ns.TSL}},"SBY":{{ns.SBY}}}', icon='mdi:download'),
                ],
            },
            2: {
                'device_config': dcfg(),
                'entities': [
                    sensor('av', vt('AV'), state_class='measurement', unit='%'),
                    sensor('spi', vt('SPI'), state_class='measurement'),
                    sensor('vsp', vt('VSP'), state_class='measurement', unit='%'),
                ],
            },
            3: {
                'device_config': dcfg(),
                'entities': [
                    sensor('av', vt('AV'), state_class='measurement', unit='%'),
                    sensor('tmp', vt('TMP'), device_class='temperature', state_class='measurement', unit='°C'),
                    sensor('sps', vt('SPS'), state_class='measurement'),
                    sensor('ats', vt('ATS'), state_class='measurement', unit='% or °C'),
                    sensor('tmprc', vt('TMPRC'), device_class='temperature', state_class='measurement', unit='°C'),
                ],
            },
            5: {
                'device_config': dcfg(),
                'entities': [
                    sensor('asp', vt('ASP'), state_class='measurement'),
                    sensor('aspt', vt('ASPT'), state_class='measurement'),
                    sensor('e_nbat', "{{ value_json['E-NBAT'] }}", device_class='battery', state_class='measurement'),
                    sensor('e_ncom', "{{ value_json['E-NCOM'] }}", state_class='measurement'),
                    sensor('e_sens', "{{ value_json['E-SENS'] }}", state_class='measurement'),
                    sensor('e_fspd', "{{ value_json['E-FSPD'] }}", state_class='measurement'),
                    sensor('err', vt('ERR'), state_class='measurement'),
                    sensor('fltr', vt('FLTR'), state_class='measurement'),
                    sensor('auto', vt('AUTO'), state_class='measurement'),
                    sensor('bpass', vt('BPASS'), state_class='measurement'),
                    sensor('frost', vt('FROST'), state_class='measurement'),
                    sensor('nsp', vt('NSP'), state_class='measurement'),
                    sensor('nspt', vt('NSPT'), state_class='measurement'),
                    sensor('rste', vt('RSTE'), state_class='measurement'),
                    sensor('rstf', vt('RSTF'), state_class='measurement'),
                ],
            },
            16: {
                'device_config': dcfg(),
                'entities': [
                    sensor('md', vt('MD'), state_class='measurement'),
                    sensor('vps', vt('VPS'), state_class='measurement'),
                    sensor('fansp', vt('FANSP'), state_class='measurement'),
                    sensor('cvar', vt('CVAR'), state_class='measurement', unit='%'),
                    binary('ro', vt('RO'), device_class='occupancy'),
                    sensor('o_i', "{{ value_json['O/I'] }}", state_class='measurement'),
                ],
            },
            17: {
                'device_config': dcfg(),
                'entities': [
                    sensor('drc', vt('DRC'), state_class='measurement'),
                    sensor('exds', vt('EXDS'), state_class='measurement'),
                    binary('wc', vt('WC'), device_class='window'),
                    sensor('rcd', vt('RCD'), state_class='measurement'),
                    sensor('err', vt('ERR'), state_class='measurement', unit='N/A'),
                    sensor('res', vt('RES'), state_class='measurement'),
                    sensor('od', vt('OD'), state_class='measurement'),
                    binary('wcd', vt('WCD'), device_class='window'),
                    sensor('kcd', vt('KCD'), state_class='measurement'),
                    sensor('ed', vt('ED'), state_class='measurement'),
                    sensor('as', vt('AS'), state_class='measurement'),
                ],
            },
            18: {
                'device_config': dcfg(),
                'entities': [
                    sensor('cv', vt('CV'), state_class='measurement', unit='%'),
                    sensor('fanor', vt('FANOR'), state_class='measurement'),
                    sensor('sps', vt('SPS'), state_class='measurement', unit='°K'),
                    sensor('ctm', vt('CTM'), state_class='measurement'),
                    sensor('cst', vt('CST'), state_class='measurement'),
                    sensor('erh', vt('ERH'), device_class='energy', state_class='total_increasing'),
                    binary('ro', vt('RO'), device_class='occupancy'),
                ],
            },
        },
        56: {
            8: {
                'device_config': dcfg(command='COM'),
                'entities': [
                    entity('switch', 'switch_COM1', command_topic='req', payload_on='{"COM":"1","TIM":"0","LCK":"0","DEL":"0","SW":"1","send":"clear"}\n', payload_off='{"COM":"1","TIM":"0","LCK":"0","DEL":"0","SW":"0","send":"clear"}\n', device_class='outlet', enabled_by_default='false'),
                    entity('light', 'light_COM1', schema='template', command_topic='req', command_on_template='{"COM":"1","TIM":"0","LCK":"0","DEL":"0","SW":"1","send":"clear"}', command_off_template='{"COM":"1","TIM":"0","LCK":"0","DEL":"0","SW":"0","send":"clear"}'),
                    entity('light', 'light_COM2', schema='template', command_topic='req', command_on_template='{"COM":"2","EDIM":"100","RMP":"1","EDIMR":"0","STR":"0","SW":"1","send":"clear"}', command_off_template='{"COM":"2","EDIM":"0","RMP":"1","EDIMR":"0","STR":"0","SW":"0","send":"clear"}'),
                ],
            },
            9: {
                'device_config': dcfg(),
                'entities': [
                    sensor('p1', vt('P1'), state_class='measurement'),
                    sensor('p2', vt('P2'), state_class='measurement'),
                    sensor('p3', vt('P3'), state_class='measurement'),
                    sensor('func', vt('FUNC'), state_class='measurement'),
                    sensor('ssf', vt('SSF'), state_class='measurement'),
                    sensor('sfv', vt('SFV'), state_class='measurement'),
                    sensor('smf', vt('SMF'), state_class='measurement'),
                ],
            },
        },
        63: {
            0: {
                'device_config': dcfg(),
                'entities': [
                    sensor('msgid', vt('MSGID'), state_class='measurement'),
                    sensor('msgs', vt('MSGS'), state_class='measurement'),
                    sensor('stcnt', vt('STCNT'), state_class='measurement'),
                    sensor('rslv', vt('RSLV'), state_class='measurement'),
                    sensor('mc_msb', "{{ value_json['MC-MSB'] }}", state_class='measurement'),
                    sensor('mc_lsb', "{{ value_json['MC-LSB'] }}", state_class='measurement'),
                ],
            },
            127: {
                'device_config': dcfg(),
                'entities': [
                    sensor('db3', vt('DB3'), state_class='measurement'),
                    sensor('db2', vt('DB2'), state_class='measurement'),
                    sensor('db1', vt('DB1'), state_class='measurement'),
                    sensor('db0', vt('DB0'), state_class='measurement'),
                ],
            },
        },
    },
}
