"""Port: the persistent device store (MQTT-discovery bookkeeping + cover positions)."""

from __future__ import annotations

from typing import Any, Protocol


class DeviceStorePort(Protocol):
    """The device-store surface the HA overlay uses (a document store keyed by uid/address/name)."""

    def db_get_device_by_field(self, field_name: str, field: Any) -> Any: ...

    def db_get_device_by_name(self, name: str) -> Any: ...

    def db_list_from_fields(self, field: str) -> list: ...

    def db_upsert_device(
        self, sensor: Any, uid: str, attr_name: Any = None, attr: Any = None
    ) -> None: ...

    def db_remove_device_by_address(self, address: Any) -> None: ...

    def db_remove_device_by_field(self, field_name: str, field: Any) -> None: ...

    def get_position(self, address: Any) -> Any: ...

    def set_position(self, address: Any, position: Any) -> None: ...

    def get_rlc(self, address: Any) -> Any: ...

    def set_rlc(self, address: Any, rlc: Any = None, rlc_snd: Any = None) -> None: ...
